{
  "kind": "Policy",
  "apiVersion": "v1",
  "predicates": [
    { "name": "PodFitsResources" },
    { "name": "HostName" },
    { "name": "PodFitsHostPorts" },
    { "name": "MatchNodeSelector" },
    { "name": "NoDiskConflict" },
    { "name": "PodToleratesNodeTaints" },
    { "name": "MaxEBSVolumeCount" },
    { "name": "MaxGCEPDVolumeCount" },
    { "name": "MaxAzureDiskVolumeCount" },
    { "name": "CheckVolumeBinding" },
    { "name": "NoVolumeZoneConflict" },
    { "name": "MatchInterPodAffinity" }
  ],
  "priorities": [
    { "name": "NodePreferAvoidPodsPriority",  "weight": 161051 },
    { "name": "NodeAffinityPriority",         "weight": 14641 },
    { "name": "InterPodAffinityPriority",     "weight": 1331 },
    { "name": "MostRequestedPriority",        "weight": 121 },
    { "name": "ImageLocalityPriority",        "weight": 11}
  ],
  "hardPodAffinitySymmetricWeight" : 100,
  "alwaysCheckAllPredicates" : false
}

# # Notes about ranges
# ImageLocalityPriority       - ranges from 0-10 * 11
# MostRequestedPriority       - ranges from 0-10 * 11^2
# InterPodAffinityPriority    - ranges from 0-1  * 11^3 (i guess)
# NodeAffinityPriority        - ranges from 0-1  * 11^4 (i guess)
# NodePreferAvoidPodsPriority - ranges from 0-1  * 11^5 (i guess)

# # Notes about the GeneralPredicates
# The following predicates was not found by kube-scheduler 1.11.1-beta.0
# { "name": "CheckNodePIDPressure" },
# { "name": "CheckNodeUnschedulable" },
# { "name": "CheckNodeCondition" },
# { "name": "General" },
# { "name": "PodToleratesNodeNoExecuteTaints" },
# { "name": "CheckNodeMemoryPressure" },
# { "name": "CheckNodeDiskPressure" },

# # Notes about the priorities
# NodePreferAvoidPodsPriority: What does this really mean?
# HardPodAffinitySymmetricWeight: "It represents the weight of implicit
# PreferredDuringScheduling affinity rule." - preferred node affinity or preferred
# pod/anti-pod affinity or those affinities in general? How does this relate to
# the InterPodAffinityPriority and NodeAffinityPriority?

# AlwaysCheckAllPredicates: scheduler checks all the configured predicates even
# after one or more of them fails.

# GeneralPredicates checks whether noncriticalPredicates and EssentialPredicates
# pass. noncriticalPredicates are the predicates that only non-critical pods need
# and EssentialPredicates are the predicates that all pods, including critical
# pods, need

# MostRequestedPriority: Is using the default MostRequestedPriorityMap that is a
# priority function that favors nodes with most requested resources. It calculates
# the percentage of memory and CPU requested by pods scheduled on the node, and
# prioritizes based on the maximum of the average of the fraction of requested to
# capacity.

# Details: (cpu(10 * sum(requested) / capacity) + memory(10 * sum(requested) /
# capacity)) / 2

# ImageLocalityPriorityMap is a priority function that favors nodes that already
# have requested pod container's images. It will detect whether the requested
# images are present on a node, and then calculate a score ranging from 0 to 10
# based on the total size of those images. - If none of the images are present,
# this node will be given the lowest priority. - If some of the images are present
# on a node, the larger their sizes' sum, the higher the node's priority.
