# coding: utf-8

"""
    Workflows API

    Workflows API

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cloudharness_cli.workflows.models.operation_status import OperationStatus
from typing import Optional, Set
from typing_extensions import Self

class Operation(BaseModel):
    """
    represents the status of a distributed API call
    """ # noqa: E501
    message: Optional[StrictStr] = Field(default=None, description="usually set when an error occurred")
    name: Optional[StrictStr] = Field(default=None, description="operation name")
    create_time: Optional[datetime] = Field(default=None, alias="createTime")
    status: Optional[OperationStatus] = OperationStatus.PENDING
    workflow: Optional[StrictStr] = Field(default=None, description="low level representation as an Argo json")
    __properties: ClassVar[List[str]] = ["message", "name", "createTime", "status", "workflow"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Operation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "create_time",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Operation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "message": obj.get("message"),
            "name": obj.get("name"),
            "createTime": obj.get("createTime"),
            "status": obj.get("status") if obj.get("status") is not None else OperationStatus.PENDING,
            "workflow": obj.get("workflow")
        })
        return _obj


