/* tslint:disable */
/* eslint-disable */
/**
 * CloudHarness Sample API
 * CloudHarness Sample api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: cloudharness@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse202Task
 */
export interface InlineResponse202Task {
    /**
     * the url where to check the operation status
     * @type {string}
     * @memberof InlineResponse202Task
     */
    href?: string;
    /**
     * 
     * @type {string}
     * @memberof InlineResponse202Task
     */
    name?: string;
}

/**
 * Check if a given object implements the InlineResponse202Task interface.
 */
export function instanceOfInlineResponse202Task(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InlineResponse202TaskFromJSON(json: any): InlineResponse202Task {
    return InlineResponse202TaskFromJSONTyped(json, false);
}

export function InlineResponse202TaskFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse202Task {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'href': !exists(json, 'href') ? undefined : json['href'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function InlineResponse202TaskToJSON(value?: InlineResponse202Task | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'href': value.href,
        'name': value.name,
    };
}

