/* tslint:disable */
/* eslint-disable */
/**
 * CloudHarness Sample API
 * CloudHarness Sample api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: cloudharness@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SampleResource
 */
export interface SampleResource {
    /**
     * 
     * @type {number}
     * @memberof SampleResource
     */
    a: number;
    /**
     * 
     * @type {number}
     * @memberof SampleResource
     */
    b?: number;
    /**
     * 
     * @type {number}
     * @memberof SampleResource
     */
    id?: number;
}

/**
 * Check if a given object implements the SampleResource interface.
 */
export function instanceOfSampleResource(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "a" in value;

    return isInstance;
}

export function SampleResourceFromJSON(json: any): SampleResource {
    return SampleResourceFromJSONTyped(json, false);
}

export function SampleResourceFromJSONTyped(json: any, ignoreDiscriminator: boolean): SampleResource {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'a': json['a'],
        'b': !exists(json, 'b') ? undefined : json['b'],
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function SampleResourceToJSON(value?: SampleResource | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'a': value.a,
        'b': value.b,
        'id': value.id,
    };
}

