apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-ui-configmap
data:
  config.yml: |-
    kafka:
      clusters:
        - name: "cluster-{{ .Values.namespace }}"
          bootstrapServers: "{{ .Values.apps.events.kafka.name }}:9092"
    auth:
      type: disabled
    management:
      health:
        ldap:
          enabled: false