apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.events.kafka.name }}
spec:
  ports:
  - name: client
    port: {{ .Values.apps.events.kafka.port }}
    targetPort: client
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  clusterIP: None
  ports:
  - name: client
    port: {{ .Values.apps.events.kafka.port }}
    targetPort: client
  - name: controller
    port: {{ .Values.apps.events.kafka.controllerPort }}
    targetPort: controller
  selector:
    app: kafka
