# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudharness_model.models.deployment_resources_conf import DeploymentResourcesConf
from typing import Optional, Set
from typing_extensions import Self

class BackupConfig(BaseModel):
    """
    
    """ # noqa: E501
    active: Optional[StrictBool] = None
    keep_days: Optional[StrictInt] = None
    keep_weeks: Optional[StrictInt] = None
    keep_months: Optional[StrictInt] = None
    schedule: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Cron expression")
    suffix: Optional[Any] = Field(default=None, description="The file suffix added to backup files")
    volumesize: Optional[StrictStr] = Field(default=None, description="The volume size for backups (all backups share the same volume)")
    dir: Annotated[str, Field(strict=True)]
    resources: DeploymentResourcesConf
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["active", "keep_days", "keep_weeks", "keep_months", "schedule", "suffix", "volumesize", "dir", "resources"]

    @field_validator('schedule')
    def schedule_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})", value):
            raise ValueError(r"must validate the regular expression /(@(annually|yearly|monthly|weekly|daily|hourly|reboot))|(@every (\d+(ns|us|µs|ms|s|m|h))+)|((((\d+,)+\d+|(\d+(\/|-)\d+)|\d+|\*) ?){5,7})/")
        return value

    @field_validator('dir')
    def dir_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[^<>:;,?*|]+$", value):
            raise ValueError(r"must validate the regular expression /^[^<>:;,?*|]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BackupConfig from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if suffix (nullable) is None
        # and model_fields_set contains the field
        if self.suffix is None and "suffix" in self.model_fields_set:
            _dict['suffix'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackupConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "active": obj.get("active"),
            "keep_days": obj.get("keep_days"),
            "keep_weeks": obj.get("keep_weeks"),
            "keep_months": obj.get("keep_months"),
            "schedule": obj.get("schedule"),
            "suffix": obj.get("suffix"),
            "volumesize": obj.get("volumesize"),
            "dir": obj.get("dir"),
            "resources": DeploymentResourcesConf.from_dict(obj["resources"]) if obj.get("resources") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


