# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib
from cloudharness_model.models.backup_gcs_config import BackupGcsConfig
from cloudharness_model.models.backup_s3_config import BackupS3Config

class BackupOffloadConfig(CloudHarnessBaseModel):
    """
    Configuration for CNPG Barman object store backup offloading
    """ # noqa: E501
    retention_policy: Optional[StrictStr] = Field(default=None, description="Retention policy for CNPG Barman backups (e.g. 30d)", alias="retentionPolicy")
    destination_path: Optional[StrictStr] = Field(default=None, description="Barman object store destination (e.g. s3://bucket/path or gs://bucket/path)", alias="destinationPath")
    endpoint_url: Optional[StrictStr] = Field(default=None, description="Endpoint URL override for S3-compatible stores (e.g. MinIO)", alias="endpointURL")
    s3: Optional[BackupS3Config] = None
    gcs: Optional[BackupGcsConfig] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["retentionPolicy", "destinationPath", "endpointURL", "s3", "gcs"]

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of s3
        if self.s3:
            _dict['s3'] = self.s3.to_dict()
        # override the default output from pydantic by calling `to_dict()` of gcs
        if self.gcs:
            _dict['gcs'] = self.gcs.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BackupOffloadConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "retentionPolicy": obj.get("retentionPolicy"),
            "destinationPath": obj.get("destinationPath"),
            "endpointURL": obj.get("endpointURL"),
            "s3": BackupS3Config.from_dict(obj["s3"]) if obj.get("s3") is not None else None,
            "gcs": BackupGcsConfig.from_dict(obj["gcs"]) if obj.get("gcs") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


