# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib
from cloudharness_model.models.deployment_resources_conf import DeploymentResourcesConf

class DatabaseDeploymentConfig(CloudHarnessBaseModel):
    """
    
    """ # noqa: E501
    auto: Optional[StrictBool] = Field(default=None, description="When true, enables automatic template")
    name: Optional[StrictStr] = None
    type: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Define the database type.  One of (mongo, postgres, neo4j, sqlite3)")
    size: Optional[StrictStr] = Field(default=None, description="Specify database disk size")
    user: Optional[StrictStr] = Field(default=None, description="database username")
    var_pass: Optional[StrictStr] = Field(default=None, description="Database password", alias="pass")
    image_ref: Optional[StrictStr] = Field(default=None, description="Used for referencing images from the build")
    mongo: Optional[Dict[str, Any]] = None
    postgres: Optional[Dict[str, Any]] = None
    neo4j: Optional[Any] = Field(default=None, description="Neo4j database specific configuration")
    resources: Optional[DeploymentResourcesConf] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auto", "name", "type", "size", "user", "pass", "image_ref", "mongo", "postgres", "neo4j", "resources"]

    @field_validator('type')
    def type_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^(mongo|postgres|neo4j|sqlite3)$", value):
            raise ValueError(r"must validate the regular expression /^(mongo|postgres|neo4j|sqlite3)$/")
        return value

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if neo4j (nullable) is None
        # and model_fields_set contains the field
        if self.neo4j is None and "neo4j" in self.model_fields_set:
            _dict['neo4j'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DatabaseDeploymentConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auto": obj.get("auto"),
            "name": obj.get("name"),
            "type": obj.get("type"),
            "size": obj.get("size"),
            "user": obj.get("user"),
            "pass": obj.get("pass"),
            "image_ref": obj.get("image_ref"),
            "mongo": obj.get("mongo"),
            "postgres": obj.get("postgres"),
            "neo4j": obj.get("neo4j"),
            "resources": DeploymentResourcesConf.from_dict(obj["resources"]) if obj.get("resources") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


