# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib
from cloudharness_model.models.deployment_resources_conf import DeploymentResourcesConf
from cloudharness_model.models.deployment_volume_spec import DeploymentVolumeSpec
from cloudharness_model.models.extra_container_config import ExtraContainerConfig
from cloudharness_model.models.network_config import NetworkConfig

class DeploymentAutoArtifactConfig(CloudHarnessBaseModel):
    """
    
    """ # noqa: E501
    auto: Optional[StrictBool] = Field(default=None, description="When true, enables automatic template")
    name: Optional[StrictStr] = None
    port: Optional[Any] = Field(default=None, description="Deployment port")
    replicas: Optional[StrictInt] = Field(default=None, description="Number of replicas")
    image: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="Image name to use in the deployment. Leave it blank to set from the application's Docker file")
    resources: Optional[DeploymentResourcesConf] = None
    volume: Optional[DeploymentVolumeSpec] = None
    statefulset: Optional[StrictBool] = Field(default=None, description="When true, the workload is rendered as a Kubernetes StatefulSet instead of a Deployment. Recommended for deployments with a ReadWriteOnce volume: updates terminate the old pod before creating the new one, so no Recreate strategy or node pinning is needed. The volume, unless ReadWriteMany or externally managed (auto false), is provisioned per replica through volumeClaimTemplates. A pre-existing PVC named after the volume (left over from a previous Deployment) is migrated automatically: a migration job streams its data into each statefulset volume through the Kubernetes API, so the volumes are never mounted by the same pod (works on multi-zone clusters); delete the legacy PVC once migrated.")
    network: Optional[NetworkConfig] = None
    extra_containers: Optional[Dict[str, ExtraContainerConfig]] = Field(default=None, description="Extra containers (init containers and sidecars) for the deployment. Each key is a container name mapping to an ExtraContainerConfig.", alias="extraContainers")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auto", "name", "port", "replicas", "image", "resources", "volume", "statefulset", "network", "extraContainers"]

    @field_validator('image')
    def image_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"(?:[a-z]+\/)?([a-z]+)(?::[0-9]+)?", value):
            raise ValueError(r"must validate the regular expression /(?:[a-z]+\/)?([a-z]+)(?::[0-9]+)?/")
        return value

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of resources
        if self.resources:
            _dict['resources'] = self.resources.to_dict()
        # override the default output from pydantic by calling `to_dict()` of volume
        if self.volume:
            _dict['volume'] = self.volume.to_dict()
        # override the default output from pydantic by calling `to_dict()` of network
        if self.network:
            _dict['network'] = self.network.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in extra_containers (dict)
        _field_dict = {}
        if self.extra_containers:
            for _key_extra_containers in self.extra_containers:
                if self.extra_containers[_key_extra_containers]:
                    _field_dict[_key_extra_containers] = self.extra_containers[_key_extra_containers].to_dict()
            _dict['extraContainers'] = _field_dict
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if port (nullable) is None
        # and model_fields_set contains the field
        if self.port is None and "port" in self.model_fields_set:
            _dict['port'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentAutoArtifactConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auto": obj.get("auto"),
            "name": obj.get("name"),
            "port": obj.get("port"),
            "replicas": obj.get("replicas"),
            "image": obj.get("image"),
            "resources": DeploymentResourcesConf.from_dict(obj["resources"]) if obj.get("resources") is not None else None,
            "volume": DeploymentVolumeSpec.from_dict(obj["volume"]) if obj.get("volume") is not None else None,
            "statefulset": obj.get("statefulset"),
            "network": NetworkConfig.from_dict(obj["network"]) if obj.get("network") is not None else None,
            "extraContainers": dict(
                (_k, ExtraContainerConfig.from_dict(_v))
                for _k, _v in obj["extraContainers"].items()
            )
            if obj.get("extraContainers") is not None
            else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


