# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model.models.auto_artifact_spec import AutoArtifactSpec
import re
from cloudharness_model import util

from cloudharness_model.models.auto_artifact_spec import AutoArtifactSpec  # noqa: E501
import re  # noqa: E501

class DeploymentAutoArtifactConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, port=None, replicas=None, image=None, resources=None, auto=None, name=None):  # noqa: E501
        """DeploymentAutoArtifactConfig - a model defined in OpenAPI

        :param port: The port of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type port: object
        :param replicas: The replicas of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type replicas: int
        :param image: The image of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type image: str
        :param resources: The resources of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type resources: object
        :param auto: The auto of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type auto: bool
        :param name: The name of this DeploymentAutoArtifactConfig.  # noqa: E501
        :type name: str
        """
        self.openapi_types = {
            'port': object,
            'replicas': int,
            'image': str,
            'resources': object,
            'auto': bool,
            'name': str
        }

        self.attribute_map = {
            'port': 'port',
            'replicas': 'replicas',
            'image': 'image',
            'resources': 'resources',
            'auto': 'auto',
            'name': 'name'
        }

        self._port = port
        self._replicas = replicas
        self._image = image
        self._resources = resources
        self._auto = auto
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'DeploymentAutoArtifactConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeploymentAutoArtifactConfig of this DeploymentAutoArtifactConfig.  # noqa: E501
        :rtype: DeploymentAutoArtifactConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def port(self):
        """Gets the port of this DeploymentAutoArtifactConfig.

        Deployment port  # noqa: E501

        :return: The port of this DeploymentAutoArtifactConfig.
        :rtype: object
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this DeploymentAutoArtifactConfig.

        Deployment port  # noqa: E501

        :param port: The port of this DeploymentAutoArtifactConfig.
        :type port: object
        """

        self._port = port

    @property
    def replicas(self):
        """Gets the replicas of this DeploymentAutoArtifactConfig.

        Number of replicas  # noqa: E501

        :return: The replicas of this DeploymentAutoArtifactConfig.
        :rtype: int
        """
        return self._replicas

    @replicas.setter
    def replicas(self, replicas):
        """Sets the replicas of this DeploymentAutoArtifactConfig.

        Number of replicas  # noqa: E501

        :param replicas: The replicas of this DeploymentAutoArtifactConfig.
        :type replicas: int
        """

        self._replicas = replicas

    @property
    def image(self):
        """Gets the image of this DeploymentAutoArtifactConfig.

        Image name to use in the deployment. Leave it blank to set from the application's Docker file  # noqa: E501

        :return: The image of this DeploymentAutoArtifactConfig.
        :rtype: str
        """
        return self._image

    @image.setter
    def image(self, image):
        """Sets the image of this DeploymentAutoArtifactConfig.

        Image name to use in the deployment. Leave it blank to set from the application's Docker file  # noqa: E501

        :param image: The image of this DeploymentAutoArtifactConfig.
        :type image: str
        """
        if image is not None and not re.search(r'(?:[a-z]+\/)?([a-z]+)(?::[0-9]+)?', image):  # noqa: E501
            raise ValueError("Invalid value for `image`, must be a follow pattern or equal to `/(?:[a-z]+\/)?([a-z]+)(?::[0-9]+)?/`")  # noqa: E501

        self._image = image

    @property
    def resources(self):
        """Gets the resources of this DeploymentAutoArtifactConfig.

        Deployment resources  # noqa: E501

        :return: The resources of this DeploymentAutoArtifactConfig.
        :rtype: object
        """
        return self._resources

    @resources.setter
    def resources(self, resources):
        """Sets the resources of this DeploymentAutoArtifactConfig.

        Deployment resources  # noqa: E501

        :param resources: The resources of this DeploymentAutoArtifactConfig.
        :type resources: object
        """

        self._resources = resources

    @property
    def auto(self):
        """Gets the auto of this DeploymentAutoArtifactConfig.

        When true, enables automatic template  # noqa: E501

        :return: The auto of this DeploymentAutoArtifactConfig.
        :rtype: bool
        """
        return self._auto

    @auto.setter
    def auto(self, auto):
        """Sets the auto of this DeploymentAutoArtifactConfig.

        When true, enables automatic template  # noqa: E501

        :param auto: The auto of this DeploymentAutoArtifactConfig.
        :type auto: bool
        """
        if auto is None:
            raise ValueError("Invalid value for `auto`, must not be `None`")  # noqa: E501

        self._auto = auto

    @property
    def name(self):
        """Gets the name of this DeploymentAutoArtifactConfig.


        :return: The name of this DeploymentAutoArtifactConfig.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DeploymentAutoArtifactConfig.


        :param name: The name of this DeploymentAutoArtifactConfig.
        :type name: str
        """

        self._name = name
