# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib

class DeploymentVolumeSpec(CloudHarnessBaseModel):
    """
    Defines a volume attached to the deployment. Automatically created the volume claim and mounts.
    """ # noqa: E501
    auto: Optional[StrictBool] = Field(default=None, description="When true, enables automatic template")
    name: Optional[StrictStr] = None
    mountpath: StrictStr = Field(description="The mount path for the volume")
    size: Optional[Any] = Field(default=None, description="The volume size.   E.g. 5Gi")
    usenfs: Optional[StrictBool] = Field(default=None, description="Deprecated: use `writeMany` with the nfs storage class instead.  Set to `true` to use the nfs on the created volume and mount as ReadWriteMany.")
    write_many: Optional[StrictBool] = Field(default=None, description="Set to `true` to create and mount the volume as ReadWriteMany.  ReadWriteMany volumes attach to several nodes at once, hence pods using them are not pinned to the volume's node. Requires a storage class supporting ReadWriteMany: set `storageClass`, unless the cluster default one supports it.", alias="writeMany")
    storage_class: Optional[StrictStr] = Field(default=None, description="The storage class used to create the volume claim. Defaults to `standard` when not specified.  Set it to null to omit the storage class from the claim, so that the cluster default storage class is used.", alias="storageClass")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["auto", "name", "mountpath", "size", "usenfs", "writeMany", "storageClass"]

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict['size'] = None

        # set to None if storage_class (nullable) is None
        # and model_fields_set contains the field
        if self.storage_class is None and "storage_class" in self.model_fields_set:
            _dict['storageClass'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeploymentVolumeSpec from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auto": obj.get("auto"),
            "name": obj.get("name"),
            "mountpath": obj.get("mountpath"),
            "size": obj.get("size"),
            "usenfs": obj.get("usenfs"),
            "writeMany": obj.get("writeMany"),
            "storageClass": obj.get("storageClass")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


