from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model.models.cpu_memory_config import CpuMemoryConfig
from cloudharness_model import util

from cloudharness_model.models.cpu_memory_config import CpuMemoryConfig  # noqa: E501

class DeploymentResourcesConf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, requests=None, limits=None):  # noqa: E501
        """DeploymentResourcesConf - a model defined in OpenAPI

        :param requests: The requests of this DeploymentResourcesConf.  # noqa: E501
        :type requests: CpuMemoryConfig
        :param limits: The limits of this DeploymentResourcesConf.  # noqa: E501
        :type limits: CpuMemoryConfig
        """
        self.openapi_types = {
            'requests': CpuMemoryConfig,
            'limits': CpuMemoryConfig
        }

        self.attribute_map = {
            'requests': 'requests',
            'limits': 'limits'
        }

        self._requests = requests
        self._limits = limits

    @classmethod
    def from_dict(cls, dikt) -> 'DeploymentResourcesConf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DeploymentResourcesConf of this DeploymentResourcesConf.  # noqa: E501
        :rtype: DeploymentResourcesConf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def requests(self) -> CpuMemoryConfig:
        """Gets the requests of this DeploymentResourcesConf.


        :return: The requests of this DeploymentResourcesConf.
        :rtype: CpuMemoryConfig
        """
        return self._requests

    @requests.setter
    def requests(self, requests: CpuMemoryConfig):
        """Sets the requests of this DeploymentResourcesConf.


        :param requests: The requests of this DeploymentResourcesConf.
        :type requests: CpuMemoryConfig
        """

        self._requests = requests

    @property
    def limits(self) -> CpuMemoryConfig:
        """Gets the limits of this DeploymentResourcesConf.


        :return: The limits of this DeploymentResourcesConf.
        :rtype: CpuMemoryConfig
        """
        return self._limits

    @limits.setter
    def limits(self, limits: CpuMemoryConfig):
        """Sets the limits of this DeploymentResourcesConf.


        :param limits: The limits of this DeploymentResourcesConf.
        :type limits: CpuMemoryConfig
        """

        self._limits = limits
