# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib
from cloudharness_model.models.application_config import ApplicationConfig
from cloudharness_model.models.backup_config import BackupConfig
from cloudharness_model.models.ingress_config import IngressConfig
from cloudharness_model.models.name_value import NameValue
from cloudharness_model.models.registry_config import RegistryConfig

class HarnessMainConfig(CloudHarnessBaseModel):
    """
    
    """ # noqa: E501
    local: StrictBool = Field(description="If set to true, local DNS mapping is added to pods.")
    secured_gatekeepers: StrictBool = Field(description="Enables/disables Gatekeepers on secured applications. Set to false for testing/development")
    domain: StrictStr = Field(description="The root domain")
    namespace: StrictStr = Field(description="The K8s namespace.")
    mainapp: StrictStr = Field(description="Defines the app to map to the root domain")
    registry: Optional[RegistryConfig] = None
    tag: Optional[StrictStr] = Field(default=None, description="Docker tag used to push/pull the built images.")
    apps: Dict[str, ApplicationConfig]
    env: Optional[List[NameValue]] = Field(default=None, description="Environmental variables added to all pods")
    privenv: Optional[List[NameValue]] = Field(default=None, description="Private environmental variables added to all pods")
    backup: Optional[BackupConfig] = None
    name: Optional[StrictStr] = Field(default=None, description="Base name")
    task_images: Optional[Dict[str, Any]] = Field(default=None, alias="task-images")
    build_hash: Optional[StrictStr] = None
    ingress: Optional[IngressConfig] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["local", "secured_gatekeepers", "domain", "namespace", "mainapp", "registry", "tag", "apps", "env", "privenv", "backup", "name", "task-images", "build_hash", "ingress"]

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of registry
        if self.registry:
            _dict['registry'] = self.registry.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each value in apps (dict)
        _field_dict = {}
        if self.apps:
            for _key_apps in self.apps:
                if self.apps[_key_apps]:
                    _field_dict[_key_apps] = self.apps[_key_apps].to_dict()
            _dict['apps'] = _field_dict
        # override the default output from pydantic by calling `to_dict()` of each item in env (list)
        _items = []
        if self.env:
            for _item_env in self.env:
                if _item_env:
                    _items.append(_item_env.to_dict())
            _dict['env'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in privenv (list)
        _items = []
        if self.privenv:
            for _item_privenv in self.privenv:
                if _item_privenv:
                    _items.append(_item_privenv.to_dict())
            _dict['privenv'] = _items
        # override the default output from pydantic by calling `to_dict()` of backup
        if self.backup:
            _dict['backup'] = self.backup.to_dict()
        # override the default output from pydantic by calling `to_dict()` of ingress
        if self.ingress:
            _dict['ingress'] = self.ingress.to_dict()
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of HarnessMainConfig from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "local": obj.get("local"),
            "secured_gatekeepers": obj.get("secured_gatekeepers"),
            "domain": obj.get("domain"),
            "namespace": obj.get("namespace"),
            "mainapp": obj.get("mainapp"),
            "registry": RegistryConfig.from_dict(obj["registry"]) if obj.get("registry") is not None else None,
            "tag": obj.get("tag"),
            "apps": dict(
                (_k, ApplicationConfig.from_dict(_v))
                for _k, _v in obj["apps"].items()
            )
            if obj.get("apps") is not None
            else None,
            "env": [NameValue.from_dict(_item) for _item in obj["env"]] if obj.get("env") is not None else None,
            "privenv": [NameValue.from_dict(_item) for _item in obj["privenv"]] if obj.get("privenv") is not None else None,
            "backup": BackupConfig.from_dict(obj["backup"]) if obj.get("backup") is not None else None,
            "name": obj.get("name"),
            "task-images": obj.get("task-images"),
            "build_hash": obj.get("build_hash"),
            "ingress": IngressConfig.from_dict(obj["ingress"]) if obj.get("ingress") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


