# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model import util


class ServiceAutoArtifactConfigAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, port=None):  # noqa: E501
        """ServiceAutoArtifactConfigAllOf - a model defined in OpenAPI

        :param port: The port of this ServiceAutoArtifactConfigAllOf.  # noqa: E501
        :type port: int
        """
        self.openapi_types = {
            'port': int
        }

        self.attribute_map = {
            'port': 'port'
        }

        self._port = port

    @classmethod
    def from_dict(cls, dikt) -> 'ServiceAutoArtifactConfigAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ServiceAutoArtifactConfig_allOf of this ServiceAutoArtifactConfigAllOf.  # noqa: E501
        :rtype: ServiceAutoArtifactConfigAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def port(self):
        """Gets the port of this ServiceAutoArtifactConfigAllOf.

        Service port  # noqa: E501

        :return: The port of this ServiceAutoArtifactConfigAllOf.
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this ServiceAutoArtifactConfigAllOf.

        Service port  # noqa: E501

        :param port: The port of this ServiceAutoArtifactConfigAllOf.
        :type port: int
        """

        self._port = port
