# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model import util


class UnitTestsConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, enabled=None, commands=None):  # noqa: E501
        """UnitTestsConfig - a model defined in OpenAPI

        :param enabled: The enabled of this UnitTestsConfig.  # noqa: E501
        :type enabled: bool
        :param commands: The commands of this UnitTestsConfig.  # noqa: E501
        :type commands: List[str]
        """
        self.openapi_types = {
            'enabled': bool,
            'commands': List[str]
        }

        self.attribute_map = {
            'enabled': 'enabled',
            'commands': 'commands'
        }

        self._enabled = enabled
        self._commands = commands

    @classmethod
    def from_dict(cls, dikt) -> 'UnitTestsConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UnitTestsConfig of this UnitTestsConfig.  # noqa: E501
        :rtype: UnitTestsConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def enabled(self):
        """Gets the enabled of this UnitTestsConfig.


        :return: The enabled of this UnitTestsConfig.
        :rtype: bool
        """
        return self._enabled

    @enabled.setter
    def enabled(self, enabled):
        """Sets the enabled of this UnitTestsConfig.


        :param enabled: The enabled of this UnitTestsConfig.
        :type enabled: bool
        """
        if enabled is None:
            raise ValueError("Invalid value for `enabled`, must not be `None`")  # noqa: E501

        self._enabled = enabled

    @property
    def commands(self):
        """Gets the commands of this UnitTestsConfig.


        :return: The commands of this UnitTestsConfig.
        :rtype: List[str]
        """
        return self._commands

    @commands.setter
    def commands(self, commands):
        """Sets the commands of this UnitTestsConfig.


        :param commands: The commands of this UnitTestsConfig.
        :type commands: List[str]
        """
        if commands is None:
            raise ValueError("Invalid value for `commands`, must not be `None`")  # noqa: E501

        self._commands = commands
