# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from typing import Optional, Set
from typing_extensions import Self


from cloudharness_model.base_model import CloudHarnessBaseModel
from pydantic import BaseModel, Field, field_validator, StrictStr, StrictBool, StrictInt, StrictFloat
from typing import ClassVar, List, Dict, Any, Union, Optional, Annotated
import importlib

class UserGroup(CloudHarnessBaseModel):
    """
    UserGroup
    """ # noqa: E501
    access: Optional[Dict[str, Any]] = None
    attributes: Optional[Dict[str, Any]] = None
    client_roles: Optional[Dict[str, Any]] = Field(default=None, alias="clientRoles")
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    realm_roles: Optional[List[StrictStr]] = Field(default=None, alias="realmRoles")
    sub_groups: Optional[List[UserGroup]] = Field(default=None, alias="subGroups")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["access", "attributes", "clientRoles", "id", "name", "path", "realmRoles", "subGroups"]

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in sub_groups (list)
        _items = []
        if self.sub_groups:
            for _item_sub_groups in self.sub_groups:
                if _item_sub_groups:
                    _items.append(_item_sub_groups.to_dict())
            _dict['subGroups'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserGroup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access": obj.get("access"),
            "attributes": obj.get("attributes"),
            "clientRoles": obj.get("clientRoles"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "path": obj.get("path"),
            "realmRoles": obj.get("realmRoles"),
            "subGroups": [UserGroup.from_dict(_item) for _item in obj["subGroups"]] if obj.get("subGroups") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


# TODO: Rewrite to not use raise_errors
UserGroup.model_rebuild(raise_errors=False)

