# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model import util


class UserGroup(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access=None, attributes=None, client_roles=None, id=None, name=None, path=None, realm_roles=None, sub_groups=None):  # noqa: E501
        """UserGroup - a model defined in OpenAPI

        :param access: The access of this UserGroup.  # noqa: E501
        :type access: Dict[str, object]
        :param attributes: The attributes of this UserGroup.  # noqa: E501
        :type attributes: Dict[str, str]
        :param client_roles: The client_roles of this UserGroup.  # noqa: E501
        :type client_roles: Dict[str, object]
        :param id: The id of this UserGroup.  # noqa: E501
        :type id: str
        :param name: The name of this UserGroup.  # noqa: E501
        :type name: str
        :param path: The path of this UserGroup.  # noqa: E501
        :type path: str
        :param realm_roles: The realm_roles of this UserGroup.  # noqa: E501
        :type realm_roles: List[str]
        :param sub_groups: The sub_groups of this UserGroup.  # noqa: E501
        :type sub_groups: List[UserGroup]
        """
        self.openapi_types = {
            'access': Dict[str, object],
            'attributes': Dict[str, str],
            'client_roles': Dict[str, object],
            'id': str,
            'name': str,
            'path': str,
            'realm_roles': List[str],
            'sub_groups': List[UserGroup]
        }

        self.attribute_map = {
            'access': 'access',
            'attributes': 'attributes',
            'client_roles': 'clientRoles',
            'id': 'id',
            'name': 'name',
            'path': 'path',
            'realm_roles': 'realmRoles',
            'sub_groups': 'subGroups'
        }

        self._access = access
        self._attributes = attributes
        self._client_roles = client_roles
        self._id = id
        self._name = name
        self._path = path
        self._realm_roles = realm_roles
        self._sub_groups = sub_groups

    @classmethod
    def from_dict(cls, dikt) -> 'UserGroup':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserGroup of this UserGroup.  # noqa: E501
        :rtype: UserGroup
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access(self):
        """Gets the access of this UserGroup.


        :return: The access of this UserGroup.
        :rtype: Dict[str, object]
        """
        return self._access

    @access.setter
    def access(self, access):
        """Sets the access of this UserGroup.


        :param access: The access of this UserGroup.
        :type access: Dict[str, object]
        """

        self._access = access

    @property
    def attributes(self):
        """Gets the attributes of this UserGroup.


        :return: The attributes of this UserGroup.
        :rtype: Dict[str, str]
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this UserGroup.


        :param attributes: The attributes of this UserGroup.
        :type attributes: Dict[str, str]
        """

        self._attributes = attributes

    @property
    def client_roles(self):
        """Gets the client_roles of this UserGroup.


        :return: The client_roles of this UserGroup.
        :rtype: Dict[str, object]
        """
        return self._client_roles

    @client_roles.setter
    def client_roles(self, client_roles):
        """Sets the client_roles of this UserGroup.


        :param client_roles: The client_roles of this UserGroup.
        :type client_roles: Dict[str, object]
        """

        self._client_roles = client_roles

    @property
    def id(self):
        """Gets the id of this UserGroup.


        :return: The id of this UserGroup.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this UserGroup.


        :param id: The id of this UserGroup.
        :type id: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this UserGroup.


        :return: The name of this UserGroup.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this UserGroup.


        :param name: The name of this UserGroup.
        :type name: str
        """

        self._name = name

    @property
    def path(self):
        """Gets the path of this UserGroup.


        :return: The path of this UserGroup.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this UserGroup.


        :param path: The path of this UserGroup.
        :type path: str
        """

        self._path = path

    @property
    def realm_roles(self):
        """Gets the realm_roles of this UserGroup.


        :return: The realm_roles of this UserGroup.
        :rtype: List[str]
        """
        return self._realm_roles

    @realm_roles.setter
    def realm_roles(self, realm_roles):
        """Sets the realm_roles of this UserGroup.


        :param realm_roles: The realm_roles of this UserGroup.
        :type realm_roles: List[str]
        """

        self._realm_roles = realm_roles

    @property
    def sub_groups(self):
        """Gets the sub_groups of this UserGroup.


        :return: The sub_groups of this UserGroup.
        :rtype: List[UserGroup]
        """
        return self._sub_groups

    @sub_groups.setter
    def sub_groups(self, sub_groups):
        """Sets the sub_groups of this UserGroup.


        :param sub_groups: The sub_groups of this UserGroup.
        :type sub_groups: List[UserGroup]
        """

        self._sub_groups = sub_groups
