# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cloudharness_model.models.organization import Organization
from cloudharness_model.models.user_credential import UserCredential
from cloudharness_model.models.user_group import UserGroup
from typing import Optional, Set
from typing_extensions import Self

class User(BaseModel):
    """
    User
    """ # noqa: E501
    access: Optional[Dict[str, Any]] = None
    attributes: Optional[Dict[str, Any]] = None
    client_roles: Optional[Dict[str, Any]] = Field(default=None, alias="clientRoles")
    created_timestamp: Optional[StrictInt] = Field(default=None, alias="createdTimestamp")
    credentials: Optional[List[UserCredential]] = None
    disableable_credential_types: Optional[List[StrictStr]] = Field(default=None, alias="disableableCredentialTypes")
    email: Optional[StrictStr] = None
    email_verified: Optional[StrictBool] = Field(default=None, alias="emailVerified")
    enabled: Optional[StrictBool] = None
    federation_link: Optional[StrictStr] = Field(default=None, alias="federationLink")
    first_name: Optional[StrictStr] = Field(default=None, alias="firstName")
    groups: Optional[List[StrictStr]] = None
    id: Optional[StrictStr] = None
    last_name: Optional[StrictStr] = Field(default=None, alias="lastName")
    realm_roles: Optional[List[StrictStr]] = Field(default=None, alias="realmRoles")
    required_actions: Optional[List[StrictStr]] = Field(default=None, alias="requiredActions")
    service_account_client_id: Optional[StrictStr] = Field(default=None, alias="serviceAccountClientId")
    username: Optional[StrictStr] = None
    additional_properties: Optional[Any] = Field(default=None, alias="additionalProperties")
    user_groups: Optional[List[UserGroup]] = Field(default=None, alias="userGroups")
    organizations: Optional[List[Organization]] = None
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["access", "attributes", "clientRoles", "createdTimestamp", "credentials", "disableableCredentialTypes", "email", "emailVerified", "enabled", "federationLink", "firstName", "groups", "id", "lastName", "realmRoles", "requiredActions", "serviceAccountClientId", "username", "additionalProperties", "userGroups", "organizations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in credentials (list)
        _items = []
        if self.credentials:
            for _item in self.credentials:
                if _item:
                    _items.append(_item.to_dict())
            _dict['credentials'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in user_groups (list)
        _items = []
        if self.user_groups:
            for _item in self.user_groups:
                if _item:
                    _items.append(_item.to_dict())
            _dict['userGroups'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in organizations (list)
        _items = []
        if self.organizations:
            for _item in self.organizations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['organizations'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        # set to None if additional_properties (nullable) is None
        # and model_fields_set contains the field
        if self.additional_properties is None and "additional_properties" in self.model_fields_set:
            _dict['additionalProperties'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "access": obj.get("access"),
            "attributes": obj.get("attributes"),
            "clientRoles": obj.get("clientRoles"),
            "createdTimestamp": obj.get("createdTimestamp"),
            "credentials": [UserCredential.from_dict(_item) for _item in obj["credentials"]] if obj.get("credentials") is not None else None,
            "disableableCredentialTypes": obj.get("disableableCredentialTypes"),
            "email": obj.get("email"),
            "emailVerified": obj.get("emailVerified"),
            "enabled": obj.get("enabled"),
            "federationLink": obj.get("federationLink"),
            "firstName": obj.get("firstName"),
            "groups": obj.get("groups"),
            "id": obj.get("id"),
            "lastName": obj.get("lastName"),
            "realmRoles": obj.get("realmRoles"),
            "requiredActions": obj.get("requiredActions"),
            "serviceAccountClientId": obj.get("serviceAccountClientId"),
            "username": obj.get("username"),
            "additionalProperties": obj.get("additionalProperties"),
            "userGroups": [UserGroup.from_dict(_item) for _item in obj["userGroups"]] if obj.get("userGroups") is not None else None,
            "organizations": [Organization.from_dict(_item) for _item in obj["organizations"]] if obj.get("organizations") is not None else None
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


