{{- if .Values.apps.jupyterhub.singleuser.extraFiles }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.singleuser.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
type: Opaque
{{- with include "jupyterhub.extraFiles.data" .Values.apps.jupyterhub.singleuser.extraFiles }}
data:
  {{- . | nindent 2 }}
{{- end }}
{{- with include "jupyterhub.extraFiles.stringData" .Values.apps.jupyterhub.singleuser.extraFiles }}
stringData:
  {{- . | nindent 2 }}
{{- end }}
{{- end }}
