openapi: 3.0.0
info:
  description: notifications
  version: 0.1.0
  title: notifications
  contact:
    email: cloudharness@metacell.us
  license:
    name: UNLICENSED

tags:
  - name: test
  - name: live
  - name: ready
paths:
  /ping:
    get:
      summary: test the application is up
      operationId: ping
      tags:
        - test
      responses:
        "500":
          description: This shouldn't happen
        "200":
          description: What we want
          content:
            application/json:
              schema:
                type: string
  /live:
    get:
      summary: Test if application is healthy
      operationId: live
      tags:
        - live
      responses:
        "500":
          description: Application is not healthy
        "200":
          description: Healthy
          content:
            application/json:
              schema:
                type: string
  /ready:
    get:
      summary: Test if application is ready to take requests
      operationId: ready
      tags:
        - ready
      responses:
        "500":
          description: Application is not ready yet
        "200":
          description: Ready
          content:
            application/json:
              schema:
                type: string
servers:
  - url: /api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: cloudharness.auth.decode_token
  schemas:
    Valid:
      type: object
      properties:
        response:
          type: string
