# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by: https://openapi-generator.tech
"""

import unittest

import cloudharness_cli.samples
from cloudharness_cli.samples.model.inline_response202_task import InlineResponse202Task
from cloudharness_cli.samples import configuration


class TestInlineResponse202Task(unittest.TestCase):
    """InlineResponse202Task unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
