harness:
  subdomain: notifications
  secured: false
  service:
    auto: false
  deployment:
    name: notifications
    auto: true
    resources:
      requests:
        memory: 64Mi
        cpu: 25m
      limits:
        memory: 256Mi
        cpu: 100m
  dependencies:
    build:
      - cloudharness-base
  secrets:
    email-user:
    email-password:
  events:  # events the notification service is listening to
    cdc: # change data capture events, see https://devshawn.com/blog/apache-kafka-topic-naming-conventions/

notification:
  backends:
    email:
      type: email
    console:
      type: console
    slack:
      type: slack
  channels:
    email:
      type: email
      backends:
        - email
        - console
      templateFolder: email
      from: info@example.com
      to:
        - info@example.com
    console:
      type: email
      backends: 
        - console
      templateFolder: text
      from: info@example.com
      to:
        - info@example.com
  operations:
    create:
      subject: New {{message_type}} - {{domain}}
      template: model-instance-create
      channels:
        - email
    update:
      subject: Update {{message)_type}} - {{domain}}
      template: model-instance-update
      channels:
        - email
    delete:
      subject: Delete {{message)_type}} - {{domain}}
      template: model-instance-delete
      channels:
        - email
