# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.deployment_volume_spec import DeploymentVolumeSpec

class TestDeploymentVolumeSpec(unittest.TestCase):
    """DeploymentVolumeSpec unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentVolumeSpec:
        """Test DeploymentVolumeSpec
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentVolumeSpec`
        """
        model = DeploymentVolumeSpec()
        if include_optional:
            return DeploymentVolumeSpec(
                auto = True,
                name = '',
                mountpath = '',
                size = None,
                usenfs = True
            )
        else:
            return DeploymentVolumeSpec(
                auto = True,
                mountpath = '',
        )
        """

    def testDeploymentVolumeSpec(self):
        """Test DeploymentVolumeSpec"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
