# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.deployment_resources_conf import DeploymentResourcesConf

class TestDeploymentResourcesConf(unittest.TestCase):
    """DeploymentResourcesConf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentResourcesConf:
        """Test DeploymentResourcesConf
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentResourcesConf`
        """
        model = DeploymentResourcesConf()
        if include_optional:
            return DeploymentResourcesConf(
                requests = cloudharness_model.models.cpu_memory_config.CpuMemoryConfig(
                    cpu = '', 
                    memory = '', ),
                limits = cloudharness_model.models.cpu_memory_config.CpuMemoryConfig(
                    cpu = '', 
                    memory = '', )
            )
        else:
            return DeploymentResourcesConf(
        )
        """

    def testDeploymentResourcesConf(self):
        """Test DeploymentResourcesConf"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
