# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.user_credential import UserCredential

class TestUserCredential(unittest.TestCase):
    """UserCredential unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UserCredential:
        """Test UserCredential
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UserCredential`
        """
        model = UserCredential()
        if include_optional:
            return UserCredential(
                created_date = 56,
                credential_data = '',
                id = '',
                priority = 56,
                secret_data = '',
                temporary = True,
                type = '',
                user_label = '',
                value = ''
            )
        else:
            return UserCredential(
        )
        """

    def testUserCredential(self):
        """Test UserCredential"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
