# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.user import User

class TestUser(unittest.TestCase):
    """User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> User:
        """Test User
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `User`
        """
        model = User()
        if include_optional:
            return User(
                access = { },
                attributes = { },
                client_roles = { },
                created_timestamp = 56,
                credentials = [
                    cloudharness_model.models.user_credential.UserCredential(
                        created_date = 56, 
                        credential_data = '', 
                        id = '', 
                        priority = 56, 
                        secret_data = '', 
                        temporary = True, 
                        type = '', 
                        user_label = '', 
                        value = '', )
                    ],
                disableable_credential_types = [
                    ''
                    ],
                email = '',
                email_verified = True,
                enabled = True,
                federation_link = '',
                first_name = '',
                groups = [
                    ''
                    ],
                id = '',
                last_name = '',
                realm_roles = [
                    ''
                    ],
                required_actions = [
                    ''
                    ],
                service_account_client_id = '',
                username = '',
                additional_properties = None
            )
        else:
            return User(
        )
        """

    def testUser(self):
        """Test User"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
