# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.e2_e_tests_config import E2ETestsConfig

class TestE2ETestsConfig(unittest.TestCase):
    """E2ETestsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> E2ETestsConfig:
        """Test E2ETestsConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `E2ETestsConfig`
        """
        model = E2ETestsConfig()
        if include_optional:
            return E2ETestsConfig(
                enabled = True,
                smoketest = True,
                ignore_console_errors = True,
                ignore_request_errors = True
            )
        else:
            return E2ETestsConfig(
                enabled = True,
                smoketest = True,
        )
        """

    def testE2ETestsConfig(self):
        """Test E2ETestsConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
