# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.application_test_config import ApplicationTestConfig

class TestApplicationTestConfig(unittest.TestCase):
    """ApplicationTestConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApplicationTestConfig:
        """Test ApplicationTestConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApplicationTestConfig`
        """
        model = ApplicationTestConfig()
        if include_optional:
            return ApplicationTestConfig(
                unit = cloudharness_model.models.unit_tests_config.UnitTestsConfig(
                    enabled = True, 
                    commands = ["pytest /usr/src/app/samples/test"], ),
                api = cloudharness_model.models.api_tests_config.ApiTestsConfig(
                    enabled = True, 
                    autotest = True, 
                    run_params = [
                        ''
                        ], 
                    checks = ["not_a_server_error", "status_code_conformance"], ),
                e2e = cloudharness_model.models.e2_e_tests_config.E2ETestsConfig(
                    enabled = True, 
                    smoketest = True, 
                    ignore_console_errors = True, 
                    ignore_request_errors = True, )
            )
        else:
            return ApplicationTestConfig(
                unit = cloudharness_model.models.unit_tests_config.UnitTestsConfig(
                    enabled = True, 
                    commands = ["pytest /usr/src/app/samples/test"], ),
                api = cloudharness_model.models.api_tests_config.ApiTestsConfig(
                    enabled = True, 
                    autotest = True, 
                    run_params = [
                        ''
                        ], 
                    checks = ["not_a_server_error", "status_code_conformance"], ),
                e2e = cloudharness_model.models.e2_e_tests_config.E2ETestsConfig(
                    enabled = True, 
                    smoketest = True, 
                    ignore_console_errors = True, 
                    ignore_request_errors = True, ),
        )
        """

    def testApplicationTestConfig(self):
        """Test ApplicationTestConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
