# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.deployment_auto_artifact_config import DeploymentAutoArtifactConfig

class TestDeploymentAutoArtifactConfig(unittest.TestCase):
    """DeploymentAutoArtifactConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentAutoArtifactConfig:
        """Test DeploymentAutoArtifactConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentAutoArtifactConfig`
        """
        model = DeploymentAutoArtifactConfig()
        if include_optional:
            return DeploymentAutoArtifactConfig(
                auto = True,
                name = '',
                port = None,
                replicas = 56,
                image = 'iotgs/wmejtcmosllnyulewqtzioitixmoo',
                resources = cloudharness_model.models.deployment_resources_conf.DeploymentResourcesConf(
                    requests = cloudharness_model.models.cpu_memory_config.CpuMemoryConfig(
                        cpu = '', 
                        memory = '', ), 
                    limits = cloudharness_model.models.cpu_memory_config.CpuMemoryConfig(
                        cpu = '', 
                        memory = '', ), ),
                volume = {"auto":true,"mountpath":"/usr/src/app/persistent","name":"my-files","size":"5Gi","usenfs":true}
            )
        else:
            return DeploymentAutoArtifactConfig(
                auto = True,
        )
        """

    def testDeploymentAutoArtifactConfig(self):
        """Test DeploymentAutoArtifactConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
