# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.ingress_config import IngressConfig

class TestIngressConfig(unittest.TestCase):
    """IngressConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngressConfig:
        """Test IngressConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngressConfig`
        """
        model = IngressConfig()
        if include_optional:
            return IngressConfig(
                auto = True,
                name = '',
                ssl_redirect = True,
                letsencrypt = cloudharness_model.models.ingress_config_all_of_letsencrypt.IngressConfig_allOf_letsencrypt(
                    email = '', )
            )
        else:
            return IngressConfig(
                auto = True,
        )
        """

    def testIngressConfig(self):
        """Test IngressConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
