# coding: utf-8

"""
    cloudharness

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_model.models.api_tests_config import ApiTestsConfig

class TestApiTestsConfig(unittest.TestCase):
    """ApiTestsConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApiTestsConfig:
        """Test ApiTestsConfig
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApiTestsConfig`
        """
        model = ApiTestsConfig()
        if include_optional:
            return ApiTestsConfig(
                enabled = True,
                autotest = True,
                run_params = [
                    ''
                    ],
                checks = ["not_a_server_error", "status_code_conformance"]
            )
        else:
            return ApiTestsConfig(
                enabled = True,
                autotest = True,
                checks = ["not_a_server_error", "status_code_conformance"],
        )
        """

    def testApiTestsConfig(self):
        """Test ApiTestsConfig"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
