openapi: 3.0.0
info:
  description: CloudHarness Sample api
  version: 0.1.0
  title: CloudHarness Sample API
  contact:
    email: cloudharness@metacell.us
  license:
    name: UNLICENSED

tags:
  - name: auth
  - name: workflows

paths:
  /valid:
    get:
      summary: Check if the token is valid. Get a token by logging into the base url
      security:
        - bearerAuth: []
      tags:
        - auth
      operationId: valid_token
      description: |
        Check if the token is valid
      responses:
        "200":
          description: Check if token is valid
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Valid"
        "400":
          description: bad input parameter

  /error:
    get:
      summary: test sentry is working
      operationId: error
      tags:
        - workflows
      responses:
        "500":
          description: Sentry entry should come!
        "200":
          description: This won't happen
          content:
            application/json:
              schema:
                type: string


  /operation_sync:
    get:
      summary: Send a synchronous operation
      operationId: submitSync
      tags:
        - workflows
      responses:
        "200":
          description: Operation result
          content:
            application/json:
              schema:
                type: string

  /operation_sync_results:
    get:
      summary: Send a synchronous operation and get results using the event queue. Just a sum, but in the cloud
      operationId: submitSyncWithResults
      tags:
        - workflows
      parameters:
        - in: query
          name: a
          description: first number to sum
          schema:
            type: number
          example: 10
        - in: query
          name: b
          description: second number to sum
          schema:
            type: number
          example: 10
      responses:
        "200":
          description: Operation result
          content:
            application/json:
              schema:
                type: string
  /operation_async:
    get:
      summary: Send an asynchronous operation
      operationId: submitAsync
      tags:
        - workflows
      responses:
        "202":
          description: Submitted operation. See also https://restfulapi.net/http-status-202-accepted/
          content:
            application/json:
              schema:
                type: object
                properties:
                  task:
                    type: object
                    properties:
                      href:
                        description: the url where to check the operation status
                        type: string
                        example: http://workflows.cloudharness.metacell.us/api/operation/my-op
                      name:
                        type: string
                        example: my-op
servers:
  - url: https://samples.cloudharness.metacell.us/api
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: cloudharness.auth.decode_token
  schemas:
    Valid:
      type: object
      properties:
        response:
          type: string
