harness:
  subdomain: sentry
  secured: false
  service:
    auto: true
    port: 9000
    name: sentry
  deployment:
    auto: true
    name: sentry
    port: 9000
    resources:
      requests:
        memory: 256Mi
        cpu: 300m
      limits:
        memory: 2048Mi
        cpu: 2000m
  database:
    auto: true
    type: postgres
    size: 2Gi
    user: sentry
    pass: secret
    postgres:
      initialdb: sentry
  env:
  - name: SENTRY_SERVER_EMAIL
    value: zoran@metacell.us
  secrets:
    - name: ch-sentry
      key: server-email
    - name: ch-sentry
      key: email-user
    - name: ch-sentry
      key: email-password

redis:
  name: sentry-redis-host
  image: redis:latest
  port: 6379