apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  strategy:
    {{- .Values.apps.jupyterhub.hub.deploymentStrategy | toYaml | trimSuffix "\n" | nindent 4 }}
  template:
    metadata:
      labels:
        {{- /* Changes here will cause the Deployment to restart the pods. */}}
        {{- include "jupyterhub.matchLabels" . | nindent 8 }}
        hub.jupyter.org/network-access-proxy-api: "true"
        hub.jupyter.org/network-access-proxy-http: "true"
        hub.jupyter.org/network-access-singleuser: "true"
        {{- if .Values.apps.jupyterhub.hub.labels }}
        {{- .Values.apps.jupyterhub.hub.labels | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
      annotations:
        # This lets us autorestart when the secret changes!
        checksum/config-map: {{ include (print .Template.BasePath "/jupyterhub/hub/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print .Template.BasePath "/jupyterhub/hub/secret.yaml") . | sha256sum }}
        {{- if .Values.apps.jupyterhub.hub.annotations }}
        {{- .Values.apps.jupyterhub.hub.annotations | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
    spec:
      hostAliases:
        - ip: {{ .Values.localIp }}
          hostnames:
          {{ printf "- %s" .Values.domain }}
          {{- range $app := .Values.apps }}
          {{- if $app.harness.subdomain }}
          {{ printf "- %s.%s" $app.harness.subdomain "mnp.local" }}
          {{- end }}
          {{- end }}
      {{- if .Values.apps.jupyterhub.scheduling.podPriority.enabled }}
      priorityClassName: {{ .Release.Name }}-default-priority
      {{- end }}
      nodeSelector: {{ toJson .Values.apps.jupyterhub.hub.nodeSelector }}
      {{- include "jupyterhub.coreAffinity" . | nindent 6 }}
      volumes:
        - name: config
          configMap:
            name: hub-config
        - name: cloudharness-allvalues
          configMap:
            name: cloudharness-allvalues
        - name: secret
          secret:
            {{- if .Values.apps.jupyterhub.hub.existingSecret }}
            secretName: {{ .Values.apps.jupyterhub.hub.existingSecret }}
            {{- else }}
            secretName: hub-secret
            {{- end }}
        {{- if .Values.apps.jupyterhub.hub.extraVolumes }}
        {{- .Values.apps.jupyterhub.hub.extraVolumes | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
        {{- if eq .Values.apps.jupyterhub.hub.db.type "sqlite-pvc" }}
        - name: hub-db-dir
          persistentVolumeClaim:
            claimName: hub-db-dir
        {{- end }}
      {{- if .Values.apps.jupyterhub.rbac.enabled }}
      serviceAccountName: hub
      {{- end }}
      securityContext:
        fsGroup: {{ .Values.apps.jupyterhub.hub.fsGid }}
      {{- if and .Values.registry.secret (contains .Values.registry.name .Values.apps.jupyterhub.image) }}
      imagePullSecrets:
        - name: {{ .Values.registry.secret }}
      {{- end }}
      {{- if .Values.apps.jupyterhub.hub.initContainers }}
      initContainers:
        {{- .Values.apps.jupyterhub.hub.initContainers | toYaml | trimSuffix "\n" | nindent 8 }}
      {{- end }}
      containers:
        {{- if .Values.apps.jupyterhub.hub.extraContainers }}
        {{- .Values.apps.jupyterhub.hub.extraContainers | toYaml | trimSuffix "\n" | nindent 8 }}
        {{- end }}
        - name: hub
          image: {{ .Values.apps.jupyterhub.harness.deployment.image }}
          imagePullPolicy: IfNotPresent
          command:
            - jupyterhub
            - --config
            - /etc/jupyterhub/jupyterhub_config.py
            {{- if .Values.apps.jupyterhub.debug.enabled }}
            - --debug
            {{- end }}
            {{- /*
            We want to do automatic upgrades for sqlite-pvc by default, but
            allow users to opt out of that if they want. Users using their own
            db need to 'opt in' Go Templates treat nil and "" and false as
            'false', making this code complex. We can probably make this a
            one-liner, but doing combinations of boolean vars in go templates is
            very inelegant & hard to reason about.
            */}}
            {{- $upgradeType := typeOf .Values.apps.jupyterhub.hub.db.upgrade }}
            {{- if eq $upgradeType "bool" }}
            {{- /* .Values.apps.jupyterhub.hub.db.upgrade has been explicitly set to true or false */}}
            {{- if .Values.apps.jupyterhub.hub.db.upgrade }}
            - --upgrade-db
            {{- end }}
            {{- else if eq $upgradeType "<nil>" }}
            {{- /* .Values.apps.jupyterhub.hub.db.upgrade is nil */}}
            {{- if eq .Values.apps.jupyterhub.hub.db.type "sqlite-pvc" }}
            - --upgrade-db
            {{- end }}
            {{- end }}
          volumeMounts:
            - mountPath: /etc/jupyterhub/jupyterhub_config.py
              subPath: jupyterhub_config.py
              name: config
            - mountPath: /etc/jupyterhub/z2jh.py
              subPath: z2jh.py
              name: config
            - mountPath: /etc/jupyterhub/cull_idle_servers.py
              subPath: cull_idle_servers.py
              name: config
            - mountPath: /etc/jupyterhub/config/
              name: config
            - mountPath: /etc/jupyterhub/secret/
              name: secret
            - name: cloudharness-allvalues
              mountPath: /opt/cloudharness/resources/allvalues.yaml
              subPath: allvalues.yaml
            {{- if .Values.apps.jupyterhub.hub.extraVolumeMounts }}
            {{- .Values.apps.jupyterhub.hub.extraVolumeMounts | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- end }}
            {{- if eq .Values.apps.jupyterhub.hub.db.type "sqlite-pvc" }}
            - mountPath: /srv/jupyterhub
              name: hub-db-dir
              {{- if .Values.apps.jupyterhub.hub.db.pvc.subPath }}
              subPath: {{ .Values.apps.jupyterhub.hub.db.pvc.subPath | quote }}
              {{- end }}
            {{- end }}
          resources:
            {{- .Values.apps.jupyterhub.hub.resources | toYaml | trimSuffix "\n" | nindent 12 }}
          {{- with .Values.apps.jupyterhub.hub.image.pullPolicy }}
          imagePullPolicy: {{ . }}
          {{- end }}
          securityContext:
            runAsUser: {{ .Values.apps.jupyterhub.hub.uid }}
            # Don't allow any process to execute as root inside the container
            allowPrivilegeEscalation: false
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: HELM_RELEASE_NAME
              value: {{ .Release.Name | quote }}
            {{- if .Values.apps.jupyterhub.hub.cookieSecret }}
            - name: JPY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if .Values.apps.jupyterhub.hub.existingSecret }}
                  name: {{ .Values.apps.jupyterhub.hub.existingSecret }}
                  {{- else }}
                  name: hub-secret
                  {{- end }}
                  key: hub.cookie-secret
            {{- end }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIGPROXY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  {{- if .Values.apps.jupyterhub.hub.existingSecret }}
                  name: {{ .Values.apps.jupyterhub.hub.existingSecret }}
                  {{- else }}
                  name: hub-secret
                  {{- end }}
                  key: proxy.token
            {{- if .Values.apps.jupyterhub.auth.state.enabled }}
            - name: JUPYTERHUB_CRYPT_KEY
              valueFrom:
                secretKeyRef:
                  {{- if .Values.apps.jupyterhub.hub.existingSecret }}
                  name: {{ .Values.apps.jupyterhub.hub.existingSecret }}
                  {{- else }}
                  name: hub-secret
                  {{- end }}
                  key: auth.state.crypto-key
            {{- end }}
            {{- if .Values.apps.jupyterhub.hub.db.password }}
            {{- if eq .Values.apps.jupyterhub.hub.db.type "mysql" }}
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.apps.jupyterhub.hub.existingSecret }}
                  name: {{ .Values.apps.jupyterhub.hub.existingSecret }}
                  {{- else }}
                  name: hub-secret
                  {{- end }}
                  key: hub.db.password
            {{- else if eq .Values.apps.jupyterhub.hub.db.type "postgres" }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.apps.jupyterhub.hub.existingSecret }}
                  name: {{ .Values.apps.jupyterhub.hub.existingSecret }}
                  {{- else }}
                  name: hub-secret
                  {{- end }}
                  key: hub.db.password
            {{- end }}
            {{- end }}
            {{- if .Values.apps.jupyterhub.hub.extraEnv }}
            {{- $extraEnvType := typeOf .Values.apps.jupyterhub.hub.extraEnv }}
            {{- /* If we have a list, embed that here directly. This allows for complex configuration from configmap, downward API, etc. */}}
            {{- if eq $extraEnvType "[]interface {}" }}
            {{- .Values.apps.jupyterhub.hub.extraEnv | toYaml | trimSuffix "\n" | nindent 12 }}
            {{- else if eq $extraEnvType "map[string]interface {}" }}
            {{- /* If we have a map, treat those as key-value pairs. */}}
            {{- range $key, $value := .Values.apps.jupyterhub.hub.extraEnv }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- end }}
          ports:
            - containerPort: 8081
              name: hub
          {{- if .Values.apps.jupyterhub.hub.livenessProbe.enabled }}
          # livenessProbe notes:
          # We don't know how long hub database upgrades could take
          # so having a liveness probe could be a bit risky unless we put
          # a initialDelaySeconds value with long enough margin for that
          # to not be an issue. If it is too short, we could end up aborting
          # database upgrades midway or ending up in an infinite restart
          # loop.
          livenessProbe:
            initialDelaySeconds: {{ .Values.apps.jupyterhub.hub.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apps.jupyterhub.hub.livenessProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.apps.jupyterhub.hub.baseUrl | trimSuffix "/" }}/hub/health
              port: hub
          {{- end }}
          {{- if .Values.apps.jupyterhub.hub.readinessProbe.enabled }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.apps.jupyterhub.hub.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apps.jupyterhub.hub.readinessProbe.periodSeconds }}
            httpGet:
              path: {{ .Values.apps.jupyterhub.hub.baseUrl | trimSuffix "/" }}/hub/health
              port: hub
          {{- end }}
