{{- if .Values.apps.jupyterhub.hub.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: hub
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              hub.jupyter.org/network-access-hub: "true"
      ports:
        - protocol: TCP
          port: 8081
    {{- /* Useful if you want to give hub access to pods from other namespaces */}}
    {{- if .Values.apps.jupyterhub.hub.networkPolicy.ingress}}
    {{- .Values.apps.jupyterhub.hub.networkPolicy.ingress| toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
  egress:
    {{- /*
    The default is to allow all egress for hub If you want to restrict it the
    following egress is required
      -  proxy:8001
      -  singleuser:8888
      -  Kubernetes api-server
    */}}
    {{- if .Values.apps.jupyterhub.hub.networkPolicy.egress }}
    {{- .Values.apps.jupyterhub.hub.networkPolicy.egress | toYaml | trimSuffix "\n" | nindent 4 }}
    {{- end }}
{{- end }}
