{{- if .Values.apps.jupyterhub.hub.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jupyterhub.hub-serviceaccount.fullname" . }}
  {{- with .Values.apps.jupyterhub.hub.serviceAccount.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
{{- end }}
