#!/usr/bin/env python

import sys
import os

from cloudharness_utilities.codefresh import create_codefresh_deployment_scripts
from cloudharness_utilities.helm import create_helm_chart


HERE = os.path.dirname(os.path.realpath(__file__)).replace(os.path.sep, '/')
ROOT = os.path.dirname(HERE).replace(os.path.sep, '/')

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description='Walk filesystem inside ./applications and define build and deploy scripts.')
    parser.add_argument('paths', metavar='paths', default=ROOT, type=str, nargs='*',
                        help='Base paths to start looking for applications. The paths will be processed in the given order.')
    args, unknown = parser.parse_known_args(sys.argv[1:])

    if unknown:
        print('There are unknown args. Make sure to call the script with the accepted args. Try --help')
        print(f'unknown: {unknown}')
    else:
        create_codefresh_deployment_scripts(args.paths)

