#!/usr/bin/env python

import sys
import os
import shutil

from cloudharness_utilities import HERE
from cloudharness_utilities.constants import APPLICATION_TEMPLATE_PATH
import cloudharness_utilities.openapi
from cloudharness_utilities.openapi import generate_server, APPLICATIONS_SRC_PATH

APPLICATION_TEMPLATE = os.path.join(APPLICATION_TEMPLATE_PATH, 'base')

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description='Creates a new Application.')
    parser.add_argument('name', metavar='name', type=str,
                        help='Application name')
    args, unknown = parser.parse_known_args(sys.argv[1:])

    if unknown:
        print('There are unknown args. Make sure to call the script with the accepted args. Try --help')
        print(f'unknown: {unknown}')
    else:
        app_path = os.path.join(APPLICATIONS_SRC_PATH, args.name)
        shutil.copytree(APPLICATION_TEMPLATE, app_path) # TODO replace the name inside the template
        generate_server(app_path)



