#!/usr/bin/env python

import glob
import os
import shutil
import sys

from cloudharness_utilities.openapi import LIB_NAME, generate_python_client, generate_server

HERE = os.path.dirname(os.path.realpath(__file__))
ROOT = os.path.dirname(HERE)





def get_openapi_file_paths(root_path):
    return [path for path in glob.glob(root_path + '/applications/*/api/*.yaml')]

def get_modules(openapi_files):
    return [os.path.basename(os.path.dirname(os.path.dirname(path))) for path in openapi_files]

def generate_servers(root_path):
    """
    Generates server stubs
    """
    openapi_files = get_openapi_file_paths(root_path)
    modules = get_modules(openapi_files)
    for i in range(len(modules)):
        openapi_file =  openapi_files[i]
        application_root = os.path.dirname(os.path.dirname(openapi_file))
        generate_server(application_root)


def copymergedir(root_src_dir, root_dst_dir):
    """
    Does copy and merge (shutil.copytree requires that the destination does not exist)
    :param root_src_dir:
    :param root_dst_dir:
    :return:
    """
    for src_dir, dirs, files in os.walk(root_src_dir):
        dst_dir = src_dir.replace(root_src_dir, root_dst_dir, 1)
        if not os.path.exists(dst_dir):
            os.makedirs(dst_dir)
        for file_ in files:
            src_file = os.path.join(src_dir, file_)
            dst_file = os.path.join(dst_dir, file_)
            if os.path.exists(dst_file):
                os.remove(dst_file)
            shutil.copy(src_file, dst_dir)


def aggregate_packages(client_src_path):

    DOCS_PATH = os.path.join(client_src_path, 'docs')
    TEST_PATH = os.path.join(client_src_path, 'test')
    README = os.path.join(client_src_path, 'README.md')
    REQUIREMENTS = os.path.join(client_src_path, 'requirements.txt')
    TEST_REQUIREMENTS = os.path.join(client_src_path, 'test-requirements.txt')

    if not os.path.exists(DOCS_PATH):
        os.mkdir(DOCS_PATH)
    if not os.path.exists(TEST_PATH):
        os.mkdir(TEST_PATH)
    if os.path.exists(README):
        os.remove(README)
    if os.path.exists(REQUIREMENTS):
        os.remove(REQUIREMENTS)
    if os.path.exists(TEST_REQUIREMENTS):
        os.remove(TEST_REQUIREMENTS)

    req_lines_seen = set()
    test_req_lines_seen = set()

    for MODULE_TMP_PATH in glob.glob(client_src_path + '/tmp-*'):
        module = MODULE_TMP_PATH.split(f'{LIB_NAME}/tmp-')[-1]

        # Moves package

        code_dest_dir = os.path.join(client_src_path, LIB_NAME, module)
        copymergedir(os.path.join(MODULE_TMP_PATH, LIB_NAME, module), code_dest_dir)
        copymergedir(f"{MODULE_TMP_PATH}/{LIB_NAME}.{module}", code_dest_dir) #Fixes a a bug with nested packages

        # Adds Docs
        module_doc_path = os.path.join(DOCS_PATH, module)
        if not os.path.exists(module_doc_path):

            os.mkdir(module_doc_path)
        copymergedir(f"{client_src_path}/tmp-{module}/docs", module_doc_path)

        # Adds Tests
        module_test_path = os.path.join(client_src_path, 'test', module)
        copymergedir(os.path.join(MODULE_TMP_PATH, 'test'), module_test_path)



        # Merges Readme
        readme_file = f"{MODULE_TMP_PATH}/README.md"
        with open(README, 'a+') as outfile:
            with open(readme_file) as infile:
                filedata = infile.read()
                fd = filedata.replace('docs/', f'docs/{module}/')
                outfile.write(fd)

        # Merges Requirements
        # FIXME: Different package versions will remain in the output file

        requirements_file = f"{MODULE_TMP_PATH}/requirements.txt"
        outfile = open(REQUIREMENTS, "a+")
        for line in open(requirements_file, "r"):
            if line not in req_lines_seen:
                outfile.write(line)
                req_lines_seen.add(line)
        outfile.close()

        # Merges Test Requirements
        # FIXME: Different package versions will remain in the output file
        test_requirements_file = f"{MODULE_TMP_PATH}/test-requirements.txt"
        outfile = open(TEST_REQUIREMENTS, "a+")
        for line in open(test_requirements_file, "r"):
            if line not in test_req_lines_seen:
                outfile.write(line)
                test_req_lines_seen.add(line)
        outfile.close()

        # Removes Tmp Files
        shutil.rmtree(MODULE_TMP_PATH)


def generate_clients(root_path, client_lib_name=LIB_NAME):
    """
    Generates client stubs
    """
    openapi_files = get_openapi_file_paths(root_path)
    modules = get_modules(openapi_files)
    client_src_path = os.path.join(root_path, 'client', client_lib_name)
    for i in range(len(modules)):
        module = modules[i]
        openapi_file = openapi_files[i]
        generate_python_client(module, openapi_file, client_src_path, lib_name=client_lib_name)

    aggregate_packages(client_src_path)



if __name__ == "__main__":

    import argparse

    parser = argparse.ArgumentParser(
        description='Walk filesystem inside ./applications and define build and deploy scripts.')
    parser.add_argument('path', metavar='path', default=ROOT, type=str,
                        help='Base path of the application.')
    parser.add_argument('-nc', '--no-client', dest='client', action="store_false",
                        help='Specify for local deployments info and setup')
    parser.add_argument('-ns' '--no-server', dest='server', action="store_false",
                        help='Specify for local deployments info and setup')
    parser.add_argument('-cn', '--client-name', dest='client_name', action="store", default=LIB_NAME,
                        help='Specify image registry prefix')
    args, unknown = parser.parse_known_args(sys.argv[1:])

    root_path = os.path.join(os.getcwd(), args.path) if not os.path.isabs(args.path) else args.path

    if args.server:
        generate_servers(root_path)
    if args.client:
        generate_clients(root_path, args.client_name)
