#!/usr/bin/env python

import sys
import os

from cloudharness_utilities.codefresh import create_codefresh_deployment_scripts
from cloudharness_utilities.helm import create_helm_chart


HERE = os.path.dirname(os.path.realpath(__file__)).replace(os.path.sep, '/')
ROOT = os.path.dirname(HERE).replace(os.path.sep, '/')

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description='Walk filesystem inside ./applications and define build and deploy scripts.')
    parser.add_argument('path', metavar='path', default=ROOT, type=str,
                        help='Base path of the application.')
    args, unknown = parser.parse_known_args(sys.argv[1:])

    root_path = os.path.join(os.getcwd(), args.path) if not os.path.isabs(args.path) else args.path
    if unknown:
        print('There are unknown args. Make sure to call the script with the accepted args. Try --help')
        print(f'unknown: {unknown}')
    else:
        create_codefresh_deployment_scripts(root_path)

