# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workflows_api.models.base_model_ import Model
from workflows_api import util


class OperationType(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    COMPOSITEOPERATION = "CompositeOperation"
    MULTIPLECOMPOSITEOPERATION = "MultipleCompositeOperation"
    SPARKOPERATION = "SparkOperation"

    def __init__(self):  # noqa: E501
        """OperationType - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OperationType':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OperationType of this OperationType.  # noqa: E501
        :rtype: OperationType
        """
        return util.deserialize_model(dikt, cls)
