from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from workflows_api.models.base_model import Model
from workflows_api import util


class OperationStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    RUNNING = 'Running'
    ERROR = 'Error'
    SUCCEEDED = 'Succeeded'
    SKIPPED = 'Skipped'
    FAILED = 'Failed'
    def __init__(self):  # noqa: E501
        """OperationStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OperationStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OperationStatus of this OperationStatus.  # noqa: E501
        :rtype: OperationStatus
        """
        return util.deserialize_model(dikt, cls)
