harness:
  subdomain: __APP_NAME__
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  livenessProbe:
    path: /api/live
  readinessProbe:
    path: /api/ready
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask
  test:
    api:
      enabled: true
      autotest: true
      checks:
        - all