from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from volumemanager.models.base_model import Model
from volumemanager import util


class PersistentVolumeClaimCreate(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, size=None):  # noqa: E501
        """PersistentVolumeClaimCreate - a model defined in OpenAPI

        :param name: The name of this PersistentVolumeClaimCreate.  # noqa: E501
        :type name: str
        :param size: The size of this PersistentVolumeClaimCreate.  # noqa: E501
        :type size: str
        """
        self.openapi_types = {
            'name': str,
            'size': str
        }

        self.attribute_map = {
            'name': 'name',
            'size': 'size'
        }

        self._name = name
        self._size = size

    @classmethod
    def from_dict(cls, dikt) -> 'PersistentVolumeClaimCreate':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PersistentVolumeClaimCreate of this PersistentVolumeClaimCreate.  # noqa: E501
        :rtype: PersistentVolumeClaimCreate
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this PersistentVolumeClaimCreate.

        Unique name for the Persisten Volume Claim to create.  # noqa: E501

        :return: The name of this PersistentVolumeClaimCreate.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this PersistentVolumeClaimCreate.

        Unique name for the Persisten Volume Claim to create.  # noqa: E501

        :param name: The name of this PersistentVolumeClaimCreate.
        :type name: str
        """

        self._name = name

    @property
    def size(self) -> str:
        """Gets the size of this PersistentVolumeClaimCreate.

        The size of the Persistent Volume Claim to create.  # noqa: E501

        :return: The size of this PersistentVolumeClaimCreate.
        :rtype: str
        """
        return self._size

    @size.setter
    def size(self, size: str):
        """Sets the size of this PersistentVolumeClaimCreate.

        The size of the Persistent Volume Claim to create.  # noqa: E501

        :param size: The size of this PersistentVolumeClaimCreate.
        :type size: str
        """

        self._size = size
