{{- $le := .Values.ingress.letsencrypt }}
{{- if and (not .Values.local) (not (not .Values.tls)) (ne $le.enabled false) }}
{{- range $name, $data := $le.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
type: Opaque
stringData:
{{ toYaml $data | indent 2 }}
---
{{- end }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ printf "%s-%s" "letsencrypt" .Values.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email:  {{ $le.email }}
    privateKeySecretRef:
      name: {{ $le.privateKeySecretName | default "tls-secret-issuer" }}
    solvers:
{{- if $le.solvers }}
{{ toYaml $le.solvers | indent 4 }}
{{- else }}
    - http01:
        ingress:
          class: {{ .Values.ingress.ingressClass }}
{{- end }}
{{ end }}
