{{- if .Values.server.enabled -}}
{{- if .Values.server.pdb.enabled -}}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: argo-{{ .Values.server.name}}
  labels:
    app: argo-{{ .Values.server.name}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.server.pdb.minAvailable }}
  minAvailable: {{ .Values.server.pdb.minAvailable }}
  {{- else if .Values.server.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.server.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: 0
  {{- end }}
  selector:
    matchLabels:
      app: argo-{{ .Values.server.name}}
      release: {{ .Release.Name }}
{{- end -}}
{{- end -}}
