{{ if .Values.minio.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-{{ .Values.controller.name}}-minio-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-{{ .Values.controller.name}}-minio-secret
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.controller.workflowNamespaces }}
{{- $uiServiceAccount := .Values.controller.serviceAccount }}
{{- $namespace := .Release.Namespace }}
{{- range $key := .Values.controller.workflowNamespaces }}
  {{- if not (eq $key $namespace) }}
  - kind: ServiceAccount
    name: {{ $uiServiceAccount }}
    namespace: {{ $key }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}