apiVersion: rbac.authorization.k8s.io/v1
{{- if .Values.singleNamespace }}
kind: RoleBinding
{{ else }}
kind: RoleBinding
{{- end }}
metadata:
  name: argo-{{ .Values.controller.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-{{ .Values.controller.name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.controller.workflowNamespaces }}
{{- $uiServiceAccount := .Values.controller.serviceAccount }}
{{- $namespace := .Release.Namespace }}
{{- range $key := .Values.controller.workflowNamespaces }}
  {{- if not (eq $key $namespace) }}
  - kind: ServiceAccount
    name: {{ $uiServiceAccount }}
    namespace: {{ $key }}
  {{- end }}
{{- end }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-{{ .Values.controller.name }}-cluster-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-{{ .Values.controller.name }}-cluster-template
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controller.serviceAccount }}
    namespace: {{ .Release.Namespace }}
