tags:
  - name: test
paths:
  /ping:
    get:
      summary: Test the application is up
      tags:
      - test
      responses:
        "500":
          description: This shouldn't happen
        "200":
          content:
            application/json:
              schema:
                type: string
          description: What we want
      security: []
  /live:
    get:
      summary: Test if application is healthy
      tags:
      - test
      responses:
        "500":
          description: Application is not healthy
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Healthy
      security: []
  /ready:
    get:
      summary: Test if application is ready
      tags:
      - test
      responses:
        "500":
          description: Application is not ready
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Ready
      security: []
