version: '1.0'
stages:
- prepare
- build
- deploy
steps:
  main_clone:
    title: Cloning main repository...
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  x1_build_base_image:
    type: parallel
    stage: build
    steps:
      REPLACE_ME
  x2_static_build:
    type: parallel
    stage: build
    steps:
      REPLACE_ME
  x3_parallel_build:
    type: parallel
    stage: build
    steps:
      REPLACE_ME

  prepare_deployment:
    title: "Prepare helm chart"
    image: r.cfcr.io/tarelli/cloudharness-deploy
    stage: deploy
    working_directory: ./deployment
    commands:
      - python deployment-generate.py
  
  prepare_deployment_view2:
    commands:
      - 'helm template ./deployment/helm --debug -n '${{NAME}}
    environment:
      - ACTION=auth
      - KUBE_CONTEXT=${{NAME}}
    image: codefresh/cfstep-helm:2.16.1
    stage: prepare
    title: 'View helm chart'
  
  x4_deployment:
    stage: deploy
    image: 'codefresh/cfstep-helm:2.16.1'
    title: Installing chart
    environment:
      - CHART_REF=./deployment/helm
      - RELEASE_NAME=${{NAME}}
      - KUBE_CONTEXT=${{NAME}}
      - NAMESPACE=${{NAMESPACE}}
      - TILLER_NAMESPACE=kube-system
      - CHART_VERSION=0.0.1
      - HELM_REPO_USE_HTTP=false
      - HELM_REPO_CONTEXT_PATH=
      - TIMEOUT=600
      - VALUESFILE_values=./deployment/helm/values.yaml

    when:
      branch:
        only: 
          - '${{CF_BRANCH}}'