# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from cloudharness_model.models.base_model_ import Model
from cloudharness_model import util


class IngressConfigAllOfLetsencrypt(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None):  # noqa: E501
        """IngressConfigAllOfLetsencrypt - a model defined in OpenAPI

        :param email: The email of this IngressConfigAllOfLetsencrypt.  # noqa: E501
        :type email: str
        """
        self.openapi_types = {
            'email': str
        }

        self.attribute_map = {
            'email': 'email'
        }

        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'IngressConfigAllOfLetsencrypt':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The IngressConfig_allOf_letsencrypt of this IngressConfigAllOfLetsencrypt.  # noqa: E501
        :rtype: IngressConfigAllOfLetsencrypt
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self):
        """Gets the email of this IngressConfigAllOfLetsencrypt.


        :return: The email of this IngressConfigAllOfLetsencrypt.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email):
        """Sets the email of this IngressConfigAllOfLetsencrypt.


        :param email: The email of this IngressConfigAllOfLetsencrypt.
        :type email: str
        """

        self._email = email
