{{- define "deploy_utils.secret" }}
{{- if .app.harness.secrets }}
{{- $secret_name := printf "%s" .app.harness.deployment.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret_name }}
  namespace: {{ .root.Values.namespace }}
  labels:
    app: {{ .app.harness.deployment.name }}
type: Opaque
{{- $secret := (lookup "v1" "Secret" .root.Values.namespace $secret_name) }}
{{- if $secret }}
# secret already exists

stringData:
  {{- range $k, $v := .app.harness.secrets }}
    {{- if and $v (and (eq (typeOf $v) "string") (ne $v "?")) }}
  # Set secret value to value in values.yaml if specified
  {{ $k }}: {{ $v }}
    {{- else if and (eq (typeOf $v) "string") (or (eq $v "?") (not (hasKey $secret.data $k))) }}
  # Create a random secret value if not specified in values.yaml if:
  # 1. it is not set and it is not already in the deployed secret (static random secret)
  # 2. its value is ? (dynamic random secret)
  {{ $k }}: {{ randAlphaNum 20 }}
    {{- end}}
  {{- end }}
{{- else }}
# secret doesn't exist
stringData:
    {{- range $k, $v := .app.harness.secrets }}
  {{ $k }}: {{ $v | default (randAlphaNum 20) }}
    {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
---
{{- range $app := .Values.apps }}
---
  {{- include "deploy_utils.secret" (dict "root" $ "app" $app) }}
  {{- range $subapp := $app }}
  {{- if contains "map" (typeOf $subapp)  }}
    {{- if hasKey $subapp "harness" }}
---
      {{- include "deploy_utils.secret" (dict "root" $ "app" $subapp) }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}