{{- if .Values.backup.active }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "db-backups"
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.backup.volumesize }}
---
{{- end }}
{{- define "deploy_utils.database" }}
{{- if and (eq .app.harness.database.type "postgres") .app.harness.database.postgres.operator }}
{{- include "deploy_utils.database.postgres.operator" . }}
{{- else }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .app.harness.database.name | quote }}
  namespace: {{ .root.Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .app.harness.database.size }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app.harness.database.name | quote }}
  namespace: {{ .root.Values.namespace }}
  labels:
    usesvolume: {{ .app.harness.database.name }}-{{ .root.Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .app.harness.database.name | quote }}
  template:
    metadata:
      labels:
        app: {{ .app.harness.database.name | quote }}
        service: db
        usesvolume: {{ .app.harness.database.name }}-{{ .root.Values.namespace }}
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: usesvolume
                    operator: In
                    values:
                      - {{ .app.harness.database.name }}-{{ .root.Values.namespace }}
                      - {{ .app.harness.database.name }} # Obsolete, kept for backwards compatability, to be removed at a later date
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: {{ .app.harness.database.name | quote }}
        imagePullPolicy: IfNotPresent
        {{ include (print "deploy_utils.database." .app.harness.database.type) (dict "root" .root "app" .app) }}
        ports:
        {{- range $port := (index .app.harness.database .app.harness.database.type).ports }}
        - name: {{ $port.name }}
          containerPort: {{ $port.port }}
        {{- end }}
        {{- include "deploy_utils.resources" .app.harness.database.resources | nindent 8 }}
        volumeMounts:
          - name: {{ .app.harness.database.name | quote }}
            mountPath: /data/db
          {{- if eq .app.harness.database.type "postgres" }}
          - mountPath: /dev/shm
            name: dshm  
          {{- end }}  
      volumes:
      - name: {{ .app.harness.database.name | quote }}
        persistentVolumeClaim:
          claimName: {{ .app.harness.database.name | quote }}
      {{- if eq .app.harness.database.type "postgres" }}
      - emptyDir:
          medium: Memory
        name: dshm     
      {{- end }}     
---
{{- if and .root.Values.backup.active (ne .app.harness.database.type "neo4j") }}
{{- include (print "deploy_utils.database." .app.harness.database.type ".backup") . }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .app.harness.database.name | quote }}
  namespace: {{ .root.Values.namespace }}
  labels:
    app: {{ .app.harness.deployment.name | quote }}
{{ include "deploy_utils.labels" .root | indent 4 }}
spec:
  type: {{ if .app.harness.database.expose }}LoadBalancer{{ else }}ClusterIP{{ end }}
  selector:
    app: {{ .app.harness.database.name | quote }}
  ports:
  {{- range $port := (index .app.harness.database .app.harness.database.type).ports }}
  - name: {{ $port.name }}
    port: {{ $port.port }}
  {{- end }}
{{- end }}
---
{{- include "deploy_utils.database_network_policy" (dict "root" .root "app" .app) }}
{{ end }}
{{- range $app := .Values.apps }}
  {{- if  $app.harness.database  }}
    {{- if $app.harness.database.auto  }}
      {{ include "deploy_utils.database" (dict "root" $ "app" $app) }}
    {{- end }}
    {{- range $subapp := $app }}
    {{- if contains "map" (typeOf $subapp)  }}
    {{- if hasKey $subapp "harness"}}
    {{- if and (hasKey $subapp.harness "database") $subapp.harness.database.auto }}
        {{ include "deploy_utils.database" (dict "root" $ "app" $subapp) }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}
 {{- end }}