{{- $offload := .Values.backup.offload }}
{{- $hasS3Creds := and $offload.s3.region $offload.s3.accessKeyId.value $offload.s3.secretAccessKey.value }}
{{- $hasGcsCreds := and $offload.gcs.applicationCredentials.name $offload.gcs.applicationCredentials.value }}
{{- if and .Values.backup.active $offload.destinationPath (or $hasS3Creds $hasGcsCreds) }}
apiVersion: v1
kind: Secret
metadata:
  name: backup-offload-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{- if $hasS3Creds }}
  {{ $offload.s3.accessKeyId.name | default "AWS_ACCESS_KEY_ID" }}: {{ $offload.s3.accessKeyId.value | quote }}
  {{ $offload.s3.secretAccessKey.name | default "AWS_SECRET_ACCESS_KEY" }}: {{ $offload.s3.secretAccessKey.value | quote }}
  {{- end }}
  {{- if $hasGcsCreds }}
  {{ $offload.gcs.applicationCredentials.name | default "APPLICATION_CREDENTIALS" }}: {{ $offload.gcs.applicationCredentials.value | toJson }}
  {{- end }}
{{- end }}
