{{- /*
We replace the secrets with empty values in the configmap
*/ -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloudharness-allvalues
  labels:
    app: cloudharness
data:
  allvalues.yaml: |
{{- $values_copy := deepCopy .Values }}
{{- $registry := get $values_copy "registry" }}
{{- if $registry }}
  {{- $secret := get $registry "secret" }}
  {{- if and (kindIs "map" $secret) (not (empty $secret.value)) }}
    {{- $tmp := set $registry "secret" nil }}
  {{- end }}
{{- end }}
{{- range $key, $val := .Values.apps }}
  {{- $app := get $values_copy.apps $key }}
  {{- $tmp := set $app.harness "secrets" dict }}
  {{- if $app.harness.database }}
    {{- $tmp := unset $app.harness.database "external_connect_string" }}
  {{- end }}
{{- end }}
{{ $values_copy | toYaml | indent 4 }}