{{- /*
We replace the secrets with empty values in the configmap
*/ -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: cloudharness-allvalues
  labels:
    app: cloudharness
data:
  allvalues.yaml: |
{{- $values_copy := deepCopy .Values }}
{{- range $key, $val := .Values.apps }}
  {{- $app := get $values_copy.apps $key }}
  {{- $tmp := set $app.harness "secrets" dict }}
{{- end }}
{{ $values_copy | toYaml | indent 4 }}