{{- define "deploy_utils.ingress.http" }}
  {{ $root := .root }}
  {{ $domain := .root.Values.domain }}
  {{ $secured_gatekeepers := and .root.Values.secured_gatekeepers }}
  {{ $app := .app }}
  {{ $subdomain := .subdomain }}
    http:
      paths:
      {{- if and $app.harness.secured $secured_gatekeepers $app.harness.uri_role_mapping (eq $app.harness.gateway.pathType "Prefix") }}
        {{- range $mapping := $app.harness.uri_role_mapping }}
          {{- if and (hasKey $mapping "white-listed") (index $mapping "white-listed") }}
            {{- $uri := $mapping.uri }}
            {{- if eq $uri "/" }}
      - path: /
        pathType: {{ $app.harness.gateway.pathType | default $root.Values.ingress.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ $app.harness.service.name | quote }}
            port:
              number: {{ $app.harness.service.port | default 80 }}
            {{- else if hasSuffix "/*" $uri }}
              {{- $cleanPath := trimSuffix "/*" $uri }}
              {{- $pathWithoutSlash := trimPrefix "/" $cleanPath }}
      - path: {{ printf "%s%s" $app.harness.gateway.path $pathWithoutSlash }}
        pathType: Prefix
        backend:
          service:
            name: {{ $app.harness.service.name | quote }}
            port:
              number: {{ $app.harness.service.port | default 80 }}
            {{- else if (not (contains "*" $uri)) }}
              {{- $pathWithoutSlash := trimPrefix "/" $uri }}
      - path: {{ printf "%s%s" $app.harness.gateway.path $pathWithoutSlash }}
        pathType: Exact
        backend:
          service:
            name: {{ $app.harness.service.name | quote }}
            port:
              number: {{ $app.harness.service.port | default 80 }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      - path: {{ $app.harness.gateway.path | default $root.Values.ingress.path | default "/" }}
        pathType: {{ $app.harness.gateway.pathType | default $root.Values.ingress.pathType | default "Prefix" }}
        backend:
          service:
            name: {{ if (and $app.harness.secured $secured_gatekeepers) }}{{ printf "%s-gk" $subdomain }}{{ else }}{{ $app.harness.service.name | quote }}{{ end }}
            port:
              number: {{- if (and $app.harness.secured $secured_gatekeepers) }} 8080 {{- else }} {{ $app.harness.service.port | default 80 }}{{- end }}
{{- end }}
{{- define "deploy_utils.ingress.service" }}
  {{ $domain := .root.Values.domain }}
  {{ $secured_gatekeepers := and .root.Values.secured_gatekeepers }}
  {{ $app := get .root.Values.apps  .service_name}}
  {{ $routePattern := default .root.Values.ingress.path $app.harness.gateway.path }}
      - path: /proxy/{{ $app.harness.service.name }}/{{- if eq .root.Values.ingress.ingressClass "nginx" }}(.*){{- else }}.*{{- end }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $app.harness.service.name }}{{- if (and $app.harness.secured $secured_gatekeepers) }}-gk{{- end }}
            port:
              number: {{- if (and $app.harness.secured $secured_gatekeepers) }} 8080 {{- else }} {{ $app.harness.service.port | default 80  }}{{- end }}
{{- end }}
{{- if .Values.ingress.enabled }}
  {{- $domain := .Values.domain }}
  {{- $tls := not (not .Values.tls) }}
  {{- $mainapp := .Values.mainapp }}
  {{- range $app := .Values.apps }}
    {{- if or $app.harness.subdomain $app.harness.domain $app.harness.aliases (and $mainapp (and $app.harness.name (eq $app.harness.name $mainapp))) }}
      {{- $appIngressName := default $app.harness.name $app.harness.service.name }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $appIngressName | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ $.Values.ingress.ingressClass }} # Deprecated by Kubernetes, however still required for GKE
    {{- if and (not $.Values.local) $tls }}
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/issuer: {{ printf "%s-%s" "letsencrypt" $.Values.namespace }}
    {{- end }}
    {{- if eq $.Values.ingress.ingressClass "nginx" }}
    nginx.ingress.kubernetes.io/ssl-redirect: {{ (and $tls $.Values.ingress.ssl_redirect) | quote }}
    nginx.ingress.kubernetes.io/proxy-body-size: '{{ $.Values.proxy.payload.max }}m'
    nginx.ingress.kubernetes.io/proxy-buffer-size: '128k'
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "8"
    nginx.ingress.kubernetes.io/proxy-max-temp-file-size: "1024m"
    nginx.ingress.kubernetes.io/from-to-www-redirect: 'true'
    nginx.ingress.kubernetes.io/auth-keepalive-timeout: {{ $.Values.proxy.timeout.keepalive | quote }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ $.Values.proxy.timeout.read | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ $.Values.proxy.timeout.send | quote }}
    nginx.ingress.kubernetes.io/use-forwarded-headers: {{ $.Values.proxy.forwardedHeaders | quote }}
    {{- else if eq $.Values.ingress.ingressClass "traefik" }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-ch-body-size@kubernetescrd" $.Values.namespace }}{{ if and $tls $.Values.ingress.ssl_redirect }},{{ printf "%s-ch-ssl-redirect@kubernetescrd" $.Values.namespace }}{{ end }}
    {{- end }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClass }}
  rules:
      {{- if (and $mainapp (and $app.harness.name (eq $app.harness.name $mainapp))) }}
        {{- if ne $app.harness.subdomain "www" }}
  - host: {{ $domain | quote }}
    {{ include "deploy_utils.ingress.http" (dict "root" $ "app" $app "subdomain" $app.harness.subdomain) }}
        {{- end }}
      {{- end }}
      {{- if $app.harness.domain }}
  - host: {{ $app.harness.domain | quote }}
    {{ include "deploy_utils.ingress.http" (dict "root" $ "app" $app "subdomain" $app.harness.subdomain) }}
      {{- end }}
      {{- if $app.harness.aliases }}
        {{- range $alias := $app.harness.aliases }}
  - host: {{ printf "%s.%s" $alias $domain | quote }}
    {{ include "deploy_utils.ingress.http" (dict "root" $ "app" $app "subdomain" $alias) }}
        {{- end }}
      {{- end }}
      {{- if $app.harness.subdomain }}
  - host: {{ printf "%s.%s" $app.harness.subdomain $domain | quote }}
    {{ include "deploy_utils.ingress.http" (dict "root" $ "app" $app "subdomain" $app.harness.subdomain) }}
        {{- range $subapp := $app }}
          {{- if contains "map" (typeOf $subapp) }}
            {{- if and $subapp (hasKey $subapp "harness.subdomain") }}
  - host: {{ printf "%s.%s.%s" $subapp.harness.subdomain $app.harness.subdomain $domain | quote }}
    {{ include "deploy_utils.ingress.http" (dict "root" $ "app" $subapp "subdomain" (printf "%s.%s" $subapp.harness.subdomain $app.harness.subdomain)) }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if $tls }}
  tls:
  - hosts:
          {{- if $app.harness.subdomain }}
      - {{ printf "%s.%s" $app.harness.subdomain $domain | quote }}
          {{- end }}
          {{- if $app.harness.domain }}
            {{- if ne $app.harness.domain $domain }}
      - {{ $app.harness.domain | quote }}
            {{- end }}
          {{- end }}
          {{- if $app.harness.aliases }}
            {{- range $subdomain := $app.harness.aliases }}
      - {{ printf "%s.%s" $subdomain $domain | quote }}
            {{- end }}
          {{- end }}
          {{- if (and $mainapp (and $app.harness.name (eq $app.harness.name $mainapp))) }}
            {{- if ne $app.harness.subdomain "www" }}
      - {{ $domain | quote }}
            {{- end }}
          {{- end }}
    secretName: tls-secret
      {{- end }}
      {{- if $app.harness.use_services }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-proxy" $appIngressName | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ $.Values.ingress.ingressClass }} # Deprecated by Kubernetes, however still required for GKE
    {{- if and (not $.Values.local) $tls }}
    kubernetes.io/tls-acme: 'true'
    cert-manager.io/issuer: {{ printf "%s-%s" "letsencrypt" $.Values.namespace }}
    {{- end }}
    {{- if eq $.Values.ingress.ingressClass "nginx" }}
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-body-size: '{{ $.Values.proxy.payload.max }}m'
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ $.Values.proxy.timeout.read | quote }}
    nginx.ingress.kubernetes.io/proxy-send-timeout: {{ $.Values.proxy.timeout.send | quote }}
    nginx.ingress.kubernetes.io/use-forwarded-headers: {{ $.Values.proxy.forwardedHeaders | quote }}
    {{- else if eq $.Values.ingress.ingressClass "traefik" }}
    traefik.ingress.kubernetes.io/router.pathmatcher: "PathRegexp"
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-ch-proxy-rewrite@kubernetescrd,%s-ch-body-size@kubernetescrd" $.Values.namespace $.Values.namespace }}{{ if and $tls $.Values.ingress.ssl_redirect }},{{ printf "%s-ch-ssl-redirect@kubernetescrd" $.Values.namespace }}{{ end }}
    {{- end }}
    {{- with $.Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClass }}
  rules:
        {{- if (and $mainapp (and $app.harness.name (eq $app.harness.name $mainapp))) }}
          {{- if ne $app.harness.subdomain "www" }}
  - host: {{ $domain | quote }}
    http:
      paths:
            {{- range $service := $app.harness.use_services }}
            {{ include "deploy_utils.ingress.service" (dict "root" $ "service_name" $service.name) }}
            {{- end }}
          {{- end }}
        {{- end }}
        {{- if $app.harness.subdomain }}
  - host: {{ printf "%s.%s" $app.harness.subdomain $domain | quote }}
    http:
      paths:
            {{- range $service := $app.harness.use_services }}
            {{ include "deploy_utils.ingress.service" (dict "root" $ "service_name" $service.name) }}
            {{- end }}
        {{- end }}
        {{- if $tls }}
  tls:
  - hosts:
              {{- if $app.harness.subdomain }}
      - {{ printf "%s.%s" $app.harness.subdomain $domain | quote }}
              {{- end }}
              {{- if (and $mainapp (and $app.harness.name (eq $app.harness.name $mainapp))) }}
                {{- if ne $app.harness.subdomain "www" }}
      - {{ $domain | quote }}
                {{- end }}
              {{- end }}
    secretName: tls-secret
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
