{{- if and .Values.registry.name .Values.registry.secret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registry.secret.name | quote }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |-
    {
      "auths": {
        "{{ .Values.registry.name }}": {
          "username": "_json_key",
          "password": {{ .Values.registry.secret.value | toJson }},
          "auth": "{{ printf "_json_key:%s" .Values.registry.secret.value | b64enc }}"
        }
      }
    }
{{- end }}