{{- if and .Values.local .Values.tls }}
{{- range $app := .Values.apps }}
  {{- if or $app.harness.subdomain $app.harness.domain $app.harness.aliases }}
    {{- $appIngressName := default $app.harness.name $app.harness.service.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "tls-secret-%s" $appIngressName }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $.Files.Get "resources/certs/tls.crt" | b64enc | quote }}
  tls.key: {{ $.Files.Get "resources/certs/tls.key" | b64enc | quote }}
---
  {{- end }}
{{- end }}
{{- end }}

