# Generated by Django 3.2.11 on 2026-01-15 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudharness_django', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('kc_id', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name': 'CloudHarness Organization',
                'verbose_name_plural': 'CloudHarness Organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloudharness_django.organization')),
            ],
            options={
                'verbose_name': 'CloudHarness Organization Member',
                'verbose_name_plural': 'CloudHarness Organization Members',
            },
        ),
    ]
