# -- If set to true, local DNS mapping is added to pods.
local: false
# -- Enables/disables Gatekeeper.
secured_gatekeepers: true
# -- The root domain.
domain: ${{DOMAIN}}
# -- The K8s namespace.
namespace: ch
# -- Name of mainapp, routes incoming traffic of root `domaim` to this app.
mainapp: accounts
registry:
  # -- The docker registry.
  name: "localhost:5000"
  # -- Optional secret used for pulling from docker registry.
  secret:
# -- Docker tag used to pull images.
tag: latest
# -- List of applications.
# @default -- Will be filled automatically.
apps: {}
env:
  # -- Cloud Harness version
  - name: CH_VERSION
    value: 0.0.1
  # -- Cloud harness chart version
  - name: CH_CHART_VERSION
    value: 0.0.1
privenv:
  # -- Defines a secret as private environment variable that is injected in containers.
  - name: CH_SECRET
    value: In God we trust; all others must bring data. ― W. Edwards Deming
ingress:
  # -- Flag to enable/disalbe ingress controller.
  enabled: true
  # -- K8s Name of ingress.
  name: cloudharness-ingress
  # -- Enables/disables SSL redirect.
  ssl_redirect: true
  letsencrypt:
    # -- Email for letsencrypt.
    email: filippo@metacell.us
backup:
  # -- Flag to enable/disable backups.
  active: false
  # -- Number of days to keep backups.
  keep_days: "7"
  # -- Number of weeks to keep backups.
  keep_weeks: "4"
  # -- Number of months to keep backups.
  keep_months: "6"
  # -- Schedule as cronjob expression.
  schedule: "*/5 * * * *"
  # -- The file suffix added to backup files.
  suffix: ".gz"
  # -- The volume size for backups (all backups share the same volume)
  volumesize: "2Gi"
  # -- Target directory of backups, the mount point of the persistent volume.
  dir: "/backups"
  resources:
    requests:
      # -- K8s memory resource definition.
      memory: "32Mi"
      # -- K8s cpu resource definition.
      cpu: "25m"
    limits:
      # -- K8s memory resource definition.
      memory: "64Mi"
      # -- K8s cpu resource definition.
      cpu: "50m"
proxy:
  # -- Set to false to hide remote client headers. Will hide the client IPs in all logs
  forwardedHeaders: true
  timeout:
    # -- Timeout for proxy connections in seconds.
    send: 60
    # -- Timeout for proxy responses in seconds.
    read: 60
    keepalive: 60
  payload:
    # -- Maximum size of payload in MB
    max: 250
