harness:
  subdomain: common
  secured: false
  service:
    auto: true
    port: 8080
    name: common
  proxy:
    gatekeeper:
      replicas: 1
  deployment:
    auto: true
    name: common
    port: 8080
    resources:
      requests:
        memory: 128Mi
      limits:
        memory: 256Mi
  dependencies:
    build:
      - cloudharness-flask
  test:
    api:
      enabled: true
      autotest: true
      checks:
        - all