/* tslint:disable */
/* eslint-disable */
/**
 * CloudHarness Sample API
 * CloudHarness Sample api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: cloudharness@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WriteFile200Response,
  WriteFileRequest,
} from '../models/index';
import {
    WriteFile200ResponseFromJSON,
    WriteFile200ResponseToJSON,
    WriteFileRequestFromJSON,
    WriteFileRequestToJSON,
} from '../models/index';

export interface WriteFileOperationRequest {
    writeFileRequest?: WriteFileRequest;
}

/**
 * 
 */
export class TestApi extends runtime.BaseAPI {

    /**
     * test sentry is working
     */
    async errorRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/error`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * test sentry is working
     */
    async error(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.errorRaw(initOverrides);
        return await response.value();
    }

    /**
     * test the application is up
     */
    async pingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<number>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/ping`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<number>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * test the application is up
     */
    async ping(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<number> {
        const response = await this.pingRaw(initOverrides);
        return await response.value();
    }

    /**
     * Writes a timestamped file on the application volume and returns the name of the pod that handled the request. On a statefulset deployment, route this endpoint to the leader service to have all writes land on pod 0.
     * writes a file on the application volume
     */
    async writeFileRaw(requestParameters: WriteFileOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WriteFile200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/write-file`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: WriteFileRequestToJSON(requestParameters['writeFileRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WriteFile200ResponseFromJSON(jsonValue));
    }

    /**
     * Writes a timestamped file on the application volume and returns the name of the pod that handled the request. On a statefulset deployment, route this endpoint to the leader service to have all writes land on pod 0.
     * writes a file on the application volume
     */
    async writeFile(requestParameters: WriteFileOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WriteFile200Response> {
        const response = await this.writeFileRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
