from notifications.backends.email_backend import NotificationEmailBackend
from notifications.backends.console_backend import NotificationConsoleBackend

__all__ = [NotificationEmailBackend, NotificationConsoleBackend]
