# coding: utf-8

"""
    Volumes manager API

    CloudHarness Volumes manager API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.volumemanager.api.rest_api import RestApi


class TestRestApi(unittest.TestCase):
    """RestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RestApi()

    def tearDown(self) -> None:
        pass

    def test_pvc_name_get(self) -> None:
        """Test case for pvc_name_get

        Retrieve a Persistent Volume Claim from the Kubernetes repository.
        """
        pass

    def test_pvc_post(self) -> None:
        """Test case for pvc_post

        Create a Persistent Volume Claim in Kubernetes
        """
        pass


if __name__ == '__main__':
    unittest.main()
