# coding: utf-8

"""
    Volumes manager API

    CloudHarness Volumes manager API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import cloudharness_cli.volumemanager
from cloudharness_cli.volumemanager.model.persistent_volume_claim import PersistentVolumeClaim
from cloudharness_cli.volumemanager import configuration


class TestPersistentVolumeClaim(unittest.TestCase):
    """PersistentVolumeClaim unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
