/* tslint:disable */
/* eslint-disable */
/**
 * CloudHarness Sample API
 * CloudHarness Sample api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: cloudharness@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteFile200Response
 */
export interface WriteFile200Response {
    /**
     * 
     * @type {string}
     * @memberof WriteFile200Response
     */
    filename?: string;
    /**
     * 
     * @type {string}
     * @memberof WriteFile200Response
     */
    path?: string;
    /**
     * 
     * @type {string}
     * @memberof WriteFile200Response
     */
    hostname?: string;
}

/**
 * Check if a given object implements the WriteFile200Response interface.
 */
export function instanceOfWriteFile200Response(value: object): value is WriteFile200Response {
    return true;
}

export function WriteFile200ResponseFromJSON(json: any): WriteFile200Response {
    return WriteFile200ResponseFromJSONTyped(json, false);
}

export function WriteFile200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteFile200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'filename': json['filename'] == null ? undefined : json['filename'],
        'path': json['path'] == null ? undefined : json['path'],
        'hostname': json['hostname'] == null ? undefined : json['hostname'],
    };
}

export function WriteFile200ResponseToJSON(value?: WriteFile200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'filename': value['filename'],
        'path': value['path'],
        'hostname': value['hostname'],
    };
}

