/* tslint:disable */
/* eslint-disable */
/**
 * CloudHarness Sample API
 * CloudHarness Sample api
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: cloudharness@metacell.us
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WriteFileRequest
 */
export interface WriteFileRequest {
    /**
     * 
     * @type {string}
     * @memberof WriteFileRequest
     */
    content?: string;
}

/**
 * Check if a given object implements the WriteFileRequest interface.
 */
export function instanceOfWriteFileRequest(value: object): value is WriteFileRequest {
    return true;
}

export function WriteFileRequestFromJSON(json: any): WriteFileRequest {
    return WriteFileRequestFromJSONTyped(json, false);
}

export function WriteFileRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): WriteFileRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'] == null ? undefined : json['content'],
    };
}

export function WriteFileRequestToJSON(value?: WriteFileRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
    };
}

