version: '1.0'
stages:
- prepare
- build
- unittest
- deploy
- qa
steps:
  main_clone:
    title: Clone main repository
    type: git-clone
    stage: prepare
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_BRANCH}}'
    git: github
  post_main_clone:
    title: Post main clone
    type: parallel
    stage: prepare
    steps:
      clone_cloud_harness:
        title: Cloning cloud-harness repository...
        type: git-clone
        stage: prepare
        repo: https://github.com/MetaCell/cloud-harness.git
        revision: '${{CLOUDHARNESS_BRANCH}}'
        working_directory: .
        git: github
  prepare_deployment:
    title: Prepare helm chart
    image: python:3.12
    stage: prepare
    working_directory: .
    commands:
    - bash cloud-harness/install.sh
    - export HELM_META_ARGS="$( [ -n "${{HARNESS_CHART_NAME}}" ] && printf -- "--name
      %s " "${{HARNESS_CHART_NAME}}"; [ -n "${{HARNESS_CHART_VERSION}}" ] && printf
      -- "--chart-version %s " "${{HARNESS_CHART_VERSION}}"; [ -n "${{HARNESS_APP_VERSION}}"
      ] && printf -- "--app-version %s" "${{HARNESS_APP_VERSION}}" )"
    - harness-deployment . -n test-${{NAMESPACE_BASENAME}} -d ${{DOMAIN}} -r ${{REGISTRY}}
      -rs ${{REGISTRY_SECRET}} -e test --write-env --cache-url '${{IMAGE_CACHE_URL}}'
      -N $HELM_META_ARGS -i accounts
    - cat deployment/.env >> ${{CF_VOLUME_PATH}}/env_vars_to_export
    - cat ${{CF_VOLUME_PATH}}/env_vars_to_export
  prepare_deployment_view:
    commands:
    - helm template ./deployment/helm --debug -n test-${{NAMESPACE_BASENAME}}-${{CF_SHORT_REVISION}}
    environment:
    - ACTION=auth
    - KUBE_CONTEXT=test-${{CF_BUILD_ID}}
    image: codefresh/cfstep-helm:3.6.2
    stage: prepare
    title: View helm chart
  build_application_images_0:
    type: parallel
    stage: build
    steps:
      test-e2e:
        type: build
        stage: build
        dockerfile: Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        image_name: cloud-harness/test-e2e
        title: Test e2e
        working_directory: ./test/test-e2e
        tags:
        - '${{TEST_E2E_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_E2E_TAG_EXISTS}}', '{{TEST_E2E_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_E2E_TAG_FORCE_BUILD}}', '{{TEST_E2E_TAG_FORCE_BUILD}}')
                == false
      test-api:
        type: build
        stage: build
        dockerfile: test/test-api/Dockerfile
        registry: '${{CODEFRESH_REGISTRY}}'
        buildkit: true
        build_arguments:
        - NOCACHE=${{CF_BUILD_ID}}
        - CLOUDHARNESS_BASE=${{REGISTRY}}/cloud-harness/cloudharness-base:${{CLOUDHARNESS_BASE_TAG}}
        image_name: cloud-harness/test-api
        title: Test api
        working_directory: ./.
        tags:
        - '${{TEST_API_TAG}}'
        - '${{DEPLOYMENT_PUBLISH_TAG}}-dev'
        - '${{CF_BRANCH_TAG_NORMALIZED_LOWER_CASE}}'
        - latest
        when:
          condition:
            any:
              buildDoesNotExist: includes('${{TEST_API_TAG_EXISTS}}', '{{TEST_API_TAG_EXISTS}}')
                == true
              forceNoCache: includes('${{TEST_API_TAG_FORCE_BUILD}}', '{{TEST_API_TAG_FORCE_BUILD}}')
                == false
    title: Build parallel step 1
  deployment:
    stage: deploy
    type: helm
    working_directory: ./${{CF_REPO_NAME}}
    title: Installing chart
    arguments:
      helm_version: 3.6.2
      chart_name: deployment/helm
      release_name: test-${{NAMESPACE_BASENAME}}
      kube_context: '${{CLUSTER_NAME}}'
      namespace: test-${{NAMESPACE_BASENAME}}
      chart_version: '${{CF_SHORT_REVISION}}'
      cmd_ps: --timeout 600s --create-namespace
      custom_value_files:
      - ./deployment/helm/values.yaml
      custom_values: []
  wait_deployment:
    stage: qa
    title: Wait deployment to be ready
    image: codefresh/kubectl
    commands:
    - kubectl config use-context ${{CLUSTER_NAME}}
    - kubectl config set-context --current --namespace=test-${{NAMESPACE_BASENAME}}
    - kubectl rollout status deployment/accounts
    - sleep 60
  approval:
    type: pending-approval
    stage: qa
    title: Approve anyway and delete deployment
    description: The pipeline will fail after ${{WAIT_ON_FAIL}} minutes
    timeout:
      timeUnit: minutes
      duration: '${{WAIT_ON_FAIL}}'
      finalState: denied
    when:
      condition:
        all:
          error: '"${{FAILED}}" == "failed"'
