{{- define "events.deployment" }}
events:
  networks:
    ch:
      aliases:
        - bootstrap
        - broker
  image: {{ .Values.apps.events.kafka.image }}
  ports:
    - "9094:{{ .Values.apps.events.kafka.port }}"
  expose:
    - {{ .Values.apps.events.kafka.port }}
    - {{ .Values.apps.events.kafka.controllerPort }}
  environment:
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CLUSTER_ID={{ .Values.apps.events.kafka.clusterId }}
    - KAFKA_CFG_NODE_ID=0
    - KAFKA_CFG_PROCESS_ROLES=controller,broker
    - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    - KAFKA_CFG_LISTENERS=PLAINTEXT://:{{ .Values.apps.events.kafka.port }},CONTROLLER://:{{ .Values.apps.events.kafka.controllerPort }}
    - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://events:{{ .Values.apps.events.kafka.port }}
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
    - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@broker:{{ .Values.apps.events.kafka.controllerPort }}
    - KAFKA_CFG_LOG_DIRS=/bitnami/kafka/data
    {{- range $key, $value := .Values.apps.events.kafka.config }}
    - KAFKA_CFG_{{ $key | upper | replace "." "_" | replace "-" "_" }}={{ $value }}
    {{- end }}
{{- end }}
