apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: accounts-db
  labels:
    app: {{ .Values.apps.accounts.db.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.accounts.db.name }}
  labels:
    app: {{ .Values.apps.accounts.db.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
   - port: 5432
  selector:
   app: {{ .Values.apps.accounts.db.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.accounts.db.name }}
  labels:
    app: {{ .Values.apps.accounts.db.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apps.accounts.db.name | quote }}
{{ include "deploy_utils.labels" $ | indent 6 }}
  template:
    metadata:
      labels:
        app: {{ .Values.apps.accounts.db.name }}
{{ include "deploy_utils.labels" $ | indent 8 }}
    spec:
      containers:
      - name: {{ .Values.apps.accounts.db.name | default "keycloak-postgress" | quote }}
        image: {{ .Values.apps.accounts.db.image }}
        imagePullPolicy: "IfNotPresent"
        env:
        - name: POSTGRES_DB
          value: {{ .Values.apps.accounts.db.initialdb | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.apps.accounts.db.user | quote }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.apps.accounts.db.pass | quote }}
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
          - containerPort: 5432
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: accounts-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: accounts-db
        persistentVolumeClaim:
          claimName: accounts-db
---