{{- if .Values.apps.jupyterhub.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "jupyterhub.ingress.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  {{- with .Values.apps.jupyterhub.ingress.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.apps.jupyterhub.ingress.ingressClassName }}
  ingressClassName: "{{ . }}"
  {{- end }}
  rules:
    {{- range $host := .Values.apps.jupyterhub.ingress.hosts | default (list "") }}
    - http:
        paths:
          - path: {{ $.Values.apps.jupyterhub.hub.baseUrl | trimSuffix "/" }}/{{ $.Values.apps.jupyterhub.ingress.pathSuffix }}
            pathType: {{ $.Values.apps.jupyterhub.ingress.pathType }}
            backend:
              service:
                name: {{ include "jupyterhub.proxy-public.fullname" $ }}
                port:
                  name: http
      {{- if $host }}
      host: {{ $host | quote }}
      {{- end }}
    {{- end }}
  {{- with .Values.apps.jupyterhub.ingress.tls }}
  tls:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
