openapi: 3.0.0

servers:
  - description: Metacell host
    url: https://workflows.cloudharness.metacell.us

info:
  description: Workflows API
  version: "0.1.0"
  title: Workflows API
  contact:
    email: cloudharness@metacell.us
  license:
    name: UNLICENSED

tags:
  - name: Create and Access
    description: standard creation, listing and retrieve

paths:

  /operations:
    get:
      summary: lists operations
      operationId: listOperations
      tags:
      - Create and Access
      description: |
        see all operations for the user
      parameters:
      - in: query
        name: status
        description: filter by status
        schema:
          $ref: '#/components/schemas/OperationStatus'
        example: 'QUEUED'
      - in: query
        name: previous_search_token
        description: continue previous search (pagination chunks)
        schema:
          type: string
      - in: query
        name: limit
        description: maximum number of records to return per page
        schema:
          type: integer
          minimum: 1
          maximum: 50
          default: 10
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/OperationSearchResult'
        400:
          description: bad input parameter

  '/operations/{name}':
    get:
      summary: get operation by name
      operationId: getOperation
      tags:
      - Create and Access
      description: |
        retrieves an operation by its name
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        200:
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Operation'
        404:
          description: not found
    delete:
      summary: deletes operation by name
      operationId: deleteOperation
      tags:
      - Create and Access
      description: |
        delete operation by its name
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
          200:
            description: delete OK
          404:
            description: not found
  '/operations/{name}/logs':
    get:
      summary: get operation by name
      operationId: logOperation
      tags:
      - Create and Access
      description: |
        retrieves an operation log by its name
      parameters:
      - in: path
        name: name
        required: true
        schema:
          type: string
      responses:
        200:
          description: search results matching criteria
          content:
            text/plain:
              schema:
                type: string
                example: "Hello world"
        404:
          description: not found
components:
  schemas:
    OperationSearchResult:
      description: a list of operations with meta data about the result
      properties:
        meta:
          $ref: '#/components/schemas/SearchResultData'
        items:
          type: array
          items:
            $ref: '#/components/schemas/Operation'
    SearchResultData:
      description: describes a search
      properties:
        continueToken:
          description: token to use for pagination
          type: string
    Operation:
      description: represents the status of a distributed API call
      properties:
        message:
          type: string
          description: usually set when an error occurred
          example: ""
        name:
          type: string
          description: operation name
        createTime:
          type: string
          format: date-time
          readOnly: true
          example: "2016-08-29T09:12:33.001Z"
        status:
          $ref: '#/components/schemas/OperationStatus'
        workflow:
          type: string
          description: low level representation as an Argo json

    OperationStatus:
        type: string
        default: Pending
        enum:
          - Pending
          - Running
          - Error
          - Succeeded
          - Skipped
          - Failed