
export const PROGRESS_LOADER = '.MuiCircularProgress-root'
export const NAME_ID_FIELD = '.col-name-id'
export const DOWNLOAD_SECTION= '.btn-download-selection'
export const HELP = '#help-button'
export const TABLE= '.antibodies-table'
export const RECORD_NUMBER= '.total-elements'
export const UPDATE_DATE = 'h6.last-updated'
export const CATALOG_NUMBER_FIELD= 'div[data-field="catalogNum"]'
export const SEARCH_BAR= '.search-autocomplete'
export const SEARCH_INPUT = '.search-autocomplete input'
export const ANTIBODY_TARGET_FIELD= 'div[data-field="abTarget"]'
export const ANTIBODY_COMMENTS_FIELD= 'div[data-field="comments"]'
export const KC_USERNAME = 'input#username'
export const KC_PASSWORD = 'input#password'
export const KC_LOGIN_BUTTON = '#kc-login'
export const LOGIN_BUTTON = '.btn-login'
export const USER_MENU = '.user-menu'

export const USERNAME_TITLE= '.MuiTypography-subtitle2'
export const ADD_SUBMISSION = 'a[href = "/add"]'
export const SUBMISSION_PROGRESS_BAR= 'span[role="progressbar"][aria-valuenow="50"]'
export const NEXT_BUTTON= 'button.MuiButton-textSecondary'
export const INPUT_URL = 'input[name="url"]'
export const SUBMIT = 'button[type="submit"]'
export const INPUT_CATALOG_NUMBER= 'input[name="catalogNumber"]'
export const INPUT_VENDOR= 'input[name = "vendor"]'
export const INPUT_NAME = 'input[name = "name"]'
export const INPUT_HOST = 'input[name = "host"]'
export const INPUT_TARGET_SPECIES= 'input[name = "targetSpecies"]'
export const INPUT_ANTIBODY_TARGET= 'input[name = "antibodyTarget"]'
export const CLONALITY = '#mui-component-select-clonality'
export const CLONALITY_OPTIONS = 'li[role="option"]'
export const RECOMBINANT_CLONALITY = 'li[data-value="recombinant"]'
export const INPUT_CLONE_ID = 'input[name = "cloneID"]'
export const INPUT_ISOTYPE = 'input[name = "isotype"]'
export const INPUT_CONJUGATE = 'input[name = "conjugate"]'
export const INPUT_FORMAT = 'input[name = "format"]'
export const INPUT_UNIPROT_ID= 'input[name = "uniprotID"]'
export const INPUT_EPITOPE= 'input[name = "epitope"]'
export const INPUT_APPLICATIONS = 'input[name = "applications"]'
export const INPUT_COMMENTS = 'textarea[name = "comments"]'
export const INPUT_CITATION = 'input[name = "citation"]'
export const SUCCESSFUL_SUBMISSION= 'h1.MuiTypography-h1'
export const CLOSE_SUBMISSION= '.btn-go-to-submissions'
export const ANTIBODY_TYPE= 'button.MuiCardActionArea-root'
export const MY_SUBMISSIONS = 'button.MuiTab-labelIcon'
export const FILTER= 'button[aria-label="Select columns"]'
export const FILTER_TABLE= 'input[placeholder="Column title"]'
export const FILTER_ELEMENTS = '.MuiTypography-body1'
export const ANTIBODY_ID_FIELD= 'div[data-field="abId"]'
export const SORT = 'button[title="Sort"]'
export const TOP_BUTTONS= 'button.MuiButtonBase-root.MuiIconButton-root.MuiIconButton-sizeMedium' 
export const ACCOUNT_SUBMENU= 'ul.MuiList-padding'
export const ACCOUNT_SUBMENU_ITEMS= 'li.MuiMenuItem-gutters'
