# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.samples.models.inline_response202_task import InlineResponse202Task

class TestInlineResponse202Task(unittest.TestCase):
    """InlineResponse202Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InlineResponse202Task:
        """Test InlineResponse202Task
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InlineResponse202Task`
        """
        model = InlineResponse202Task()
        if include_optional:
            return InlineResponse202Task(
                href = 'http://workflows.cloudharness.metacell.us/api/operation/my-op',
                name = 'my-op'
            )
        else:
            return InlineResponse202Task(
        )
        """

    def testInlineResponse202Task(self):
        """Test InlineResponse202Task"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
