# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.samples.api.test_api import TestApi


class TestTestApi(unittest.TestCase):
    """TestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestApi()

    def tearDown(self) -> None:
        pass

    def test_error(self) -> None:
        """Test case for error

        test sentry is working
        """
        pass

    def test_ping(self) -> None:
        """Test case for ping

        test the application is up
        """
        pass


if __name__ == '__main__':
    unittest.main()
