# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.samples.models.sample_resource import SampleResource

class TestSampleResource(unittest.TestCase):
    """SampleResource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SampleResource:
        """Test SampleResource
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SampleResource`
        """
        model = SampleResource()
        if include_optional:
            return SampleResource(
                a = 1.337,
                b = 1.337,
                id = 1.337
            )
        else:
            return SampleResource(
                a = 1.337,
        )
        """

    def testSampleResource(self):
        """Test SampleResource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
