# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.samples.api.auth_api import AuthApi


class TestAuthApi(unittest.TestCase):
    """AuthApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthApi()

    def tearDown(self) -> None:
        pass

    def test_valid_cookie(self) -> None:
        """Test case for valid_cookie

        Check if the token is valid. Get a token by logging into the base url
        """
        pass

    def test_valid_token(self) -> None:
        """Test case for valid_token

        Check if the token is valid. Get a token by logging into the base url
        """
        pass


if __name__ == '__main__':
    unittest.main()
