harness:
    subdomain: chservice
    secured: false
    service:
      auto: true
      port: 8080
      name: chservice
    deployment:
      auto: true
      name: chservice
      port: 8080
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 200m
 