#!/usr/bin/env python

import json
import pathlib
import sys
import re
import shutil
import tempfile
import subprocess
import logging
import argparse
from typing import Union

from ch_cli_tools import CH_ROOT
from cloudharness_utils.constants import APPLICATION_TEMPLATE_PATH
from ch_cli_tools.openapi import generate_server, generate_fastapi_server, APPLICATIONS_SRC_PATH, generate_ts_client
from ch_cli_tools.utils import merge_configuration_directories, replaceindir, replace_in_file, save_yaml, \
    to_python_module, copymergedir, get_json_template, replace_in_dict
from ch_cli_tools.common_types import CloudHarnessManifest, TemplateType
from ch_cli_tools.application_builders import AppBuilderPipeline

# Only allow lowercased alphabetical characters separated by "-".
name_pattern = re.compile("[a-z]+((-)?[a-z])?")

PLACEHOLDER = '__APP_NAME__'


def main() -> None:
    app_name, templates = get_command_line_arguments()

    app_path = pathlib.Path(APPLICATIONS_SRC_PATH) / app_name
    app_path.mkdir(exist_ok=True)

    templates = normalize_templates(templates)

    pipeline = AppBuilderPipeline(app_name, app_path, templates)

    pipeline.handle_pre_merge()

    pipeline.handle_merge()
    replace_in_file(app_path / 'api' / 'config.json', PLACEHOLDER, to_python_module(app_name))
    replaceindir(app_path, PLACEHOLDER, app_name)

    pipeline.handle_post_merge()

    create_manifest_file(app_path, app_name, templates)
    call_harness_generate(app_path, app_name)


def get_command_line_arguments() -> tuple[str, list[str]]:
    parser = argparse.ArgumentParser(description='Creates a new Application.')

    parser.add_argument('name', metavar='name', type=str,
                        help='Application name')
    parser.add_argument('-t', '--template',
                        dest='templates',
                        action="append",
                        default=[TemplateType.BASE],
                        type=str,
                        help="""Add a template name.

                        Available templates:
                        - flask-server (backend flask server based on openapi)
                        - webapp (React webapp including backend and frontend)
                        - db-postgres
                        - db-neo4j
                        - db-mongo
                        - django-app (fastapi django backend based on openapi)
                        """)
    args, unknown = parser.parse_known_args(sys.argv[1:])

    if unknown:
        print('There are unknown args. Make sure to call the script with the accepted args. Try --help')
        print(f'unknown: {unknown}')
        exit(1)

    try:
        match = name_pattern.match(args.name)
        if not match:
            print("Invalid application name")
            print(
                f"Application name must start and end with lowercased alphabetical characters and may contain '-' as separator. Used expression: '{name_pattern.pattern}'")
            exit(1)
    except re.error:
        print("Invalid regex")
        exit(1)

    return args.name, args.templates


def normalize_templates(templates: list[str]) -> list[str]:
    normalized_templates = list(templates)

    if TemplateType.DJANGO_APP in normalized_templates and TemplateType.WEBAPP not in normalized_templates:
        django_app_index = normalized_templates.index(TemplateType.DJANGO_APP)
        normalized_templates.insert(django_app_index, TemplateType.WEBAPP)

    has_database_template = any(template in TemplateType.database_templates() for template in normalized_templates)
    if TemplateType.DJANGO_APP in normalized_templates and not has_database_template:
        django_app_index = normalized_templates.index(TemplateType.DJANGO_APP)
        normalized_templates.insert(django_app_index, TemplateType.DB_POSTGRES)

    return normalized_templates


def create_manifest_file(app_path: pathlib.Path, app_name: str, templates: list[Union[str, TemplateType]]) -> None:
    manifest_file = app_path / '.ch-manifest'
    manifest = CloudHarnessManifest(
        app_name=app_name,
        version='1',
        inferred=False,
        templates=[str(template) for template in templates],
    )

    logging.info('Creating manifest file')
    save_yaml(manifest_file, manifest.to_dict())


def call_harness_generate(app_path: pathlib.Path, app_name: str):
    logging.info('Running initial harness generate...')
    root_path = app_path.parent.parent
    command = ['harness-generate', 'all', '--ts-only', '--app-name', app_name, root_path]
    subprocess.run(command)


if __name__ == "__main__":
    main()
