# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from samples.models.base_model_ import Model
from samples import util


class Valid(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, response=None):  # noqa: E501
        """Valid - a model defined in OpenAPI

        :param response: The response of this Valid.  # noqa: E501
        :type response: str
        """
        self.openapi_types = {
            'response': str
        }

        self.attribute_map = {
            'response': 'response'
        }

        self._response = response

    @classmethod
    def from_dict(cls, dikt) -> 'Valid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Valid of this Valid.  # noqa: E501
        :rtype: Valid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def response(self):
        """Gets the response of this Valid.


        :return: The response of this Valid.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response):
        """Sets the response of this Valid.


        :param response: The response of this Valid.
        :type response: str
        """

        self._response = response
