from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from samples.models.base_model import Model
from samples import util


class WriteFileRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, content=None):  # noqa: E501
        """WriteFileRequest - a model defined in OpenAPI

        :param content: The content of this WriteFileRequest.  # noqa: E501
        :type content: str
        """
        self.openapi_types = {
            'content': str
        }

        self.attribute_map = {
            'content': 'content'
        }

        self._content = content

    @classmethod
    def from_dict(cls, dikt) -> 'WriteFileRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The write_file_request of this WriteFileRequest.  # noqa: E501
        :rtype: WriteFileRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def content(self) -> str:
        """Gets the content of this WriteFileRequest.


        :return: The content of this WriteFileRequest.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content: str):
        """Sets the content of this WriteFileRequest.


        :param content: The content of this WriteFileRequest.
        :type content: str
        """

        self._content = content
