{{- if .Values.apps.jupyterhub.proxy.chp.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "jupyterhub.proxy.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
spec:
  {{- if not (typeIs "<nil>" .Values.apps.jupyterhub.proxy.chp.pdb.maxUnavailable) }}
  maxUnavailable: {{ .Values.apps.jupyterhub.proxy.chp.pdb.maxUnavailable }}
  {{- end }}
  {{- if not (typeIs "<nil>" .Values.apps.jupyterhub.proxy.chp.pdb.minAvailable) }}
  minAvailable: {{ .Values.apps.jupyterhub.proxy.chp.pdb.minAvailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "jupyterhub.matchLabels" . | nindent 6 }}
{{- end }}
