openapi: 3.0.0
info:
  contact:
    email: cloudharness@metacell.us
  description: Workflows API
  license:
    name: UNLICENSED
  title: Workflows API
  version: 0.1.0
servers:
- description: Metacell host
  url: https://workflows.cloudharness.metacell.us
tags:
- description: standard creation, listing and retrieve
  name: Create and Access
paths:
  /operations:
    get:
      description: |
        see all operations for the user
      operationId: list_operations
      parameters:
      - description: filter by status
        example: QUEUED
        explode: true
        in: query
        name: status
        required: false
        schema:
          $ref: '#/components/schemas/OperationStatus'
        style: form
      - description: continue previous search (pagination chunks)
        explode: true
        in: query
        name: previous_search_token
        required: false
        schema:
          type: string
        style: form
      - description: maximum number of records to return per page
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          maximum: 50
          minimum: 1
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OperationSearchResult'
          description: search results matching criteria
        "400":
          description: bad input parameter
      summary: lists operations
      tags:
      - Create and Access
      x-openapi-router-controller: workflows_api.controllers.create_and_access_controller
  /operations/{name}:
    delete:
      description: |
        delete operation by its name
      operationId: delete_operation
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: delete OK
        "404":
          description: not found
      summary: deletes operation by name
      tags:
      - Create and Access
      x-openapi-router-controller: workflows_api.controllers.create_and_access_controller
    get:
      description: |
        retrieves an operation by its name
      operationId: get_operation
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Operation'
                type: array
          description: search results matching criteria
        "404":
          description: not found
      summary: get operation by name
      tags:
      - Create and Access
      x-openapi-router-controller: workflows_api.controllers.create_and_access_controller
  /operations/{name}/logs:
    get:
      description: |
        retrieves an operation log by its name
      operationId: log_operation
      parameters:
      - explode: false
        in: path
        name: name
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            text/plain:
              schema:
                example: Hello world
                type: string
          description: search results matching criteria
        "404":
          description: not found
      summary: get operation by name
      tags:
      - Create and Access
      x-openapi-router-controller: workflows_api.controllers.create_and_access_controller
components:
  schemas:
    OperationSearchResult:
      description: a list of operations with meta data about the result
      example:
        meta:
          continueToken: continueToken
        items:
        - workflow: workflow
          createTime: 2016-08-29T09:12:33.001Z
          name: name
          message: message
        - workflow: workflow
          createTime: 2016-08-29T09:12:33.001Z
          name: name
          message: message
      properties:
        meta:
          $ref: '#/components/schemas/SearchResultData'
        items:
          items:
            $ref: '#/components/schemas/Operation'
          type: array
    SearchResultData:
      description: describes a search
      example:
        continueToken: continueToken
      properties:
        continueToken:
          description: token to use for pagination
          type: string
    Operation:
      description: represents the status of a distributed API call
      example:
        workflow: workflow
        createTime: 2016-08-29T09:12:33.001Z
        name: name
        message: message
      properties:
        message:
          description: usually set when an error occurred
          type: string
        name:
          description: operation name
          type: string
        createTime:
          example: 2016-08-29T09:12:33.001Z
          format: date-time
          readOnly: true
          type: string
        status:
          $ref: '#/components/schemas/OperationStatus'
        workflow:
          description: low level representation as an Argo json
          type: string
    OperationStatus:
      default: Pending
      enum:
      - Pending
      - Running
      - Error
      - Succeeded
      - Skipped
      - Failed
      type: string
