{{- define "deploy_utils.secrets" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .app.harness.deployment.name }}
  labels:
    app: {{ .app.harness.deployment.name| quote }}
type: Opaque
data:
    {{- range $secret := .app.harness.secrets }}
    {{ $secret.name }}: {{ $secret.value | b64enc }}
    {{- end }}
---
{{- end }}
{{- range $app := .Values.apps }}
    {{- if and $app.harness.deployment.auto $app.harness.secrets }}
---
    {{- include "deploy_utils.secrets" (dict "root" $ "app" $app) }}
    {{- end }}
{{- end }}
