{{- define "deploy_utils.deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .app.harness.deployment.name| quote }}
  namespace: {{ .root.Values.namespace }}
  labels:
    app: {{ .app.harness.deployment.name| quote }}
{{- include "deploy_utils.labels" .root | indent 4 }}
spec:
  replicas: {{ .app.harness.deployment.replicas | default 1 }}
  selector:
    matchLabels:
      app: {{ .app.harness.deployment.name| quote }}
{{- include "deploy_utils.labels" .root | indent 6 }}
  template:
    metadata:
      {{- if .app.harvest }}
      annotations:
        co.elastic.logs/enabled: "true"
        metricbeat: "true"
      {{- end }}
      labels:
        app: {{ .app.harness.deployment.name| quote }}
{{- include "deploy_utils.labels" .root | indent 8 }}
    spec:
      {{- if and .root.Values.registry.secret (contains .root.Values.registry.name .app.harness.deployment.image) }}
      imagePullSecrets:
      - name: {{ .root.Values.registry.secret }}
      {{- end }}
      containers:
      - name: {{ .app.harness.deployment.name| default "cloudharness-docs" | quote }}
        image: {{ .app.harness.deployment.image }}
        imagePullPolicy: {{ include "deploy_utils.pullpolicy" .root }}
        env:
          {{- include "deploy_utils.env" .root | nindent 8 }}
          {{- include "deploy_utils.privenv" .root | nindent 8 }}
          {{- if .app.harness.env }}
            {{- .app.harness.env | toYaml | nindent 8 }}
          {{- end }}
          {{- if .app.harness.secrets }}
            {{- range $secret := .app.harness.secrets }}
        - name: {{ print $secret.name "-" $secret.key }}
          valueFrom:
            secretKeyRef:
              name: {{ print $secret.name }}
              key: {{ print $secret.key }}
            {{- end }}
          {{- end }}
        ports:
          - containerPort: {{ .app.harness.deployment.port | default 8080 }}
        resources:
          requests:
            memory: {{ .app.harness.deployment.resources.requests.memory | default "32Mi" }}
            cpu: {{ .app.harness.deployment.resources.requests.cpu | default "25m" }}
          limits:
            memory: {{ .app.harness.deployment.resources.limits.memory | default "64Mi" }}
            cpu: {{ .app.harness.deployment.resources.limits.cpu | default "50m" }}
        volumeMounts:
          - name: cloudharness-allvalues
            mountPath: /opt/cloudharness/resources/allvalues.yaml
            subPath: allvalues.yaml
          {{- if .app.harness.deployment.volume }}
          - name: {{ .app.harness.deployment.volume.name }}
            mountPath: {{ .app.harness.deployment.volume.mountpath }}
          {{- end }}
      volumes:
        - name: cloudharness-allvalues
          configMap:
            name: cloudharness-allvalues
        {{- if .app.harness.deployment.volume }}
        - name: {{ .app.harness.deployment.volume.name }}
          persistentVolumeClaim:
            claimName: {{ .app.harness.deployment.volume.name }}
        {{- end }}
        
---
{{- end }}
{{- range $app := .Values.apps }}
  {{- if and (hasKey $app "port") $app.harness.deployment.auto | default false  }}
---
    {{- include "deploy_utils.deployment" (dict "root" $ "app" $app) }}
    {{- end }}
  {{- range $subapp := $app }}
  {{- if contains "map" (typeOf $subapp)  }}
  {{- if hasKey $subapp "harness" }}
---
      {{- include "deploy_utils.deployment" (dict "root" $ "app" $subapp) }}
  {{- end }}
  {{- end }}
  {{- end }}
 {{- end }}