{{ if .Values.local }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tls | quote }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get "resources/certs/tls.crt" | b64enc | quote }}
  tls.key: {{ .Files.Get "resources/certs/tls.key" | b64enc | quote }}
---
{{- end }}


