# coding: utf-8

"""
    Workflows API

    Workflows API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from cloudharness_cli.workflows import schemas  # noqa: F401


class OperationStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        enum_value_to_name = {
            "Pending": "PENDING",
            "Running": "RUNNING",
            "Error": "ERROR",
            "Succeeded": "SUCCEEDED",
            "Skipped": "SKIPPED",
            "Failed": "FAILED",
        }
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("Pending")
    
    @schemas.classproperty
    def RUNNING(cls):
        return cls("Running")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("Error")
    
    @schemas.classproperty
    def SUCCEEDED(cls):
        return cls("Succeeded")
    
    @schemas.classproperty
    def SKIPPED(cls):
        return cls("Skipped")
    
    @schemas.classproperty
    def FAILED(cls):
        return cls("Failed")
