apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy: {}
  local:
    useBuildkit: true
    concurrency: 4
  artifacts: []
deploy:

  helm:
    flags:
      upgrade:
        - --install
      install:
        - --timeout=10m
    releases:
    - name: null
      chartPath: deployment/helm
      #wait: true
      #valuesFiles:
      #- helm-skaffold-values.yaml
      skipBuildDependencies: true # Skip helm dep build
      artifactOverrides:
        apps: {}
      overrides:
        apps: {}
test: []