harness:
  subdomain: __APP_NAME__
  secured: false
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  dependencies:
    build:
      - cloudharness-base
      - cloudharness-flask