# coding: utf-8

"""
    ninjatest API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.ninjatest.api.test_api import TestApi


class TestTestApi(unittest.TestCase):
    """TestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TestApi()

    def tearDown(self) -> None:
        pass

    def test_ninjatest_api_live(self) -> None:
        """Test case for ninjatest_api_live

        Live
        """
        pass

    def test_ninjatest_api_ping(self) -> None:
        """Test case for ninjatest_api_ping

        Ping
        """
        pass

    def test_ninjatest_api_ready(self) -> None:
        """Test case for ninjatest_api_ready

        Ready
        """
        pass


if __name__ == '__main__':
    unittest.main()
