apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.events.kafka.name }}
spec:
  ports:
  - port: {{ .Values.apps.events.kafka.port }}
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  clusterIP: None
  ports:
  - port: {{ .Values.apps.events.kafka.port }}
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: pzoo
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zookeeper
    storage: persistent
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: client
    port: 2181
  selector:
    app: zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zoo
spec:
  clusterIP: None
  ports:
  - name: peer
    port: 2888
  - name: leader-election
    port: 3888
  selector:
    app: zookeeper
    storage: persistent-regional