# coding: utf-8

"""
    Workflows API

    Workflows API  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudharness_cli.workflows
from cloudharness_cli.workflows.models.operation_status import OperationStatus  # noqa: E501
from cloudharness_cli.workflows.rest import ApiException

class TestOperationStatus(unittest.TestCase):
    """OperationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OperationStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudharness_cli.workflows.models.operation_status.OperationStatus()  # noqa: E501
        if include_optional :
            return OperationStatus(
            )
        else :
            return OperationStatus(
        )

    def testOperationStatus(self):
        """Test OperationStatus"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
