apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-exports
  labels:
    app: nfs-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apps.nfsserver.server.diskSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
  labels:
    app: nfs-server
    usesvolume: nfs-exports
spec:
  selector:
    matchLabels:
      app: nfs-server
  template:

    metadata:
      labels:
        app: nfs-server
        usesvolume: nfs-exports
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: usesvolume
                    operator: In
                    values:
                      - nfs-exports
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: nfs-server
        image: {{ .Values.apps.nfsserver.harness.deployment.image }}
        imagePullPolicy: IfNotPresent
        env:
        # NFS useDNS {{ .Values.apps.nfsserver.nfs.useDNS }}
        {{- if .Values.apps.nfsserver.nfs.useDNS }}
        - name: NFS_SERVER
          value: {{ printf "nfs-server.%s" .Values.namespace }}
        {{- end }}
        - name: NFS_PATH
          value: {{ .Values.apps.nfsserver.nfs.path }}
        - name: PROVISIONER_NAME
          value: {{ printf "%s-nfs-provisioner" .Values.namespace }}
        ports:
        - name: nfs
          containerPort: 2049
        - name: mountd
          containerPort: 20048
        - name: rpcbind
          containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
        - name: storage
          mountPath: /exports
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: nfs-exports
---
apiVersion: v1
kind: Service
metadata:
  name: nfs-server
  labels:
    app: nfs-server
spec:
  ports:
  - name: nfs
    port: 2049
  - name: mountd
    port: 20048
  - name: rpcbind
    port: 111
  selector:
    app: nfs-server
