{{ if .Values.apps.nfsserver.nfs.mountOptions -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ template "nfs-subdir-external-provisioner.fullname" . }}
  labels: 
    {{- include "nfs-subdir-external-provisioner.labels" . | nindent 4 }}
    nfs-subdir-external-provisioner: {{ template "nfs-subdir-external-provisioner.fullname" . }}
spec:
  capacity:
    storage: 10Mi
  volumeMode: Filesystem
  accessModes:
    - {{ .Values.apps.nfsserver.storageClass.accessModes }}
  persistentVolumeReclaimPolicy: {{ .Values.apps.nfsserver.nfs.reclaimPolicy }}
  storageClassName: ""
  {{- if .Values.apps.nfsserver.nfs.mountOptions }}
  mountOptions:
    {{- range .Values.apps.nfsserver.nfs.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  nfs:
    server: {{ .Values.apps.nfsserver.nfs.server }}
    path: {{ .Values.apps.nfsserver.nfs.path }}
{{ end -}}
