{{ if .Values.apps.nfsserver.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "nfs-subdir-external-provisioner.labels" . | nindent 4 }}
  {{- with .Values.apps.nfsserver.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ template "nfs-subdir-external-provisioner.serviceAccountName" . }}
{{- end -}}
