{{- define "nfsserver.deployment" }}
{{- $nfs := .apps.nfsserver}}

{{ $nfs.name }}:
  build:
    context: {{ $nfs.build.context }}
    dockerfile: {{ $nfs.build.dockerfile }}
  image: {{ $nfs.harness.deployment.image }}
  environment:
    # NFS useDNS? {{ $nfs.nfs.useDNS }}
    {{- if $nfs.nfs.useDNS }}
    - NFS_SERVER={{ printf "nfs-server.%s.svc.cluster.local" .namespace }}
    {{- end }}
    - NFS_PATH={{ $nfs.nfs.path }}
    - PROVISIONER_NAME={{ printf "%s-nfs-provisioner" .namespace }}
{{- end }}