{{- if .Values.apps.jupyterhub.scheduling.podPriority.enabled }}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-default-priority
  labels:
    {{- $_ := merge (dict "componentLabel" "default-priority") . }}
    {{- include "jupyterhub.labels" $_ | nindent 4 }}
  annotations:
    # PriorityClasses must be added before the other resources reference them.
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-100"
value: {{ .Values.apps.jupyterhub.scheduling.podPriority.defaultPriority }}
globalDefault: {{ .Values.apps.jupyterhub.scheduling.podPriority.globalDefault }}
description: "A default priority higher than user placeholders priority."
{{- end }}
