local: false
secured_gatekeepers: true
nameOverride: ""
fullnameOverride: ""
domain: ${{DOMAIN}}
namespace: ch
mainapp: accounts
registry:
  name: "localhost:5000"
  secret:
tag: latest
apps:
  FILL_ME
env:
  - name: CH_VERSION
    value: 0.0.1
  - name: CH_CHART_VERSION
    value: 0.0.1
privenv:
  - name: CH_SECRET
    value: In God we trust; all others must bring data. ― W. Edwards Deming
ingress:
  enabled: true
  name: cloudharness-ingress
  ssl_redirect: true
  letsencrypt:
    email: filippo@metacell.us
backup:
  active: true
  keep_days: "7"
  keep_weeks: "4"
  keep_months: "6"
  schedule: "@daily"
  suffix: ".gz"
  dir: "/backups"
  resources:
    requests:
      memory: "32Mi"
      cpu: "25m"
    limits:
      memory: "64Mi"
      cpu: "50m"