# coding: utf-8

"""
    CH common service API

    Cloud Harness Platform - Reference CH service API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.common.models.get_config200_response import GetConfig200Response

class TestGetConfig200Response(unittest.TestCase):
    """GetConfig200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetConfig200Response:
        """Test GetConfig200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetConfig200Response`
        """
        model = GetConfig200Response()
        if include_optional:
            return GetConfig200Response(
                url = '',
                realm = '',
                client_id = ''
            )
        else:
            return GetConfig200Response(
        )
        """

    def testGetConfig200Response(self):
        """Test GetConfig200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
