# coding: utf-8

"""
    CH common service API

    Cloud Harness Platform - Reference CH service API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudharness_cli.common.api.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ConfigApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConfigApi()

    def tearDown(self) -> None:
        pass

    def test_get_version(self) -> None:
        """Test case for get_version

        """
        pass


if __name__ == '__main__':
    unittest.main()
