harness:
  subdomain: samples
  secured: false
  sentry: true
  port: 80
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  env:
    - name: WORKERS
      value: "3"
  dependencies:
    soft:
      - workflows
      - events


