harness:
  subdomain: samples
  secured: true
  sentry: true
  port: 80
  service:
    port: 8080
    auto: true
  use_services:
    - name: common
  deployment:
    volume:
      name: my-shared-volume
      mountpath: /tmp/myvolume
      auto: true
      size: 10Mi
      usenfs: false
    auto: true
    port: 8080
  uri_role_mapping:
    - uri: /
      white-listed: true
    - uri: /api/error
      white-listed: true
    - uri: /api/operation_sync
      white-listed: true
    - uri: /api/operation_sync_results
      white-listed: true
    - uri: /api/ping
      white-listed: true
    - uri: /api/openapi.json
      white-listed: true
    - uri: /icon.png
      white-listed: true
    - uri: /js/*
      white-listed: true
    - uri: /assets/*
      white-listed: true
  env:
    - name: WORKERS
      value: "3"
  envmap:
    ENVIRONMENT_TEST_A: "value"
    ENVIRONMENT_TEST_B: 123
  dependencies:
    soft:
      - workflows
      - events
      - accounts
      - common
    build:
      - cloudharness-flask
      - cloudharness-frontend-build

  resources:
    - name: my-config
      src: "myConfig.json"
      dst: "/tmp/resources/myConfig.json"
    - name: example
      src: "example.yaml"
      dst: "/usr/src/app/important_config.yaml"
  secrets:
    asecret: "value"

  test:
    unit:
      enabled: true
      commands:
        - "pytest /usr/src/app/samples/test"
    e2e:
      enabled: true
      smoketest: true
      ignoreRequestErrors: false
      ignoreConsoleErrors: false
    api:
      enabled: true
      autotest: true
      checks:
        - all
      runParams:
        - "--skip-deprecated-operations"
        - "--hypothesis-suppress-health-check=too_slow"
        - "--hypothesis-deadline=180000"
        - "--request-timeout=180000"
        - "--hypothesis-max-examples=2"
        - "--show-errors-tracebacks"

  dockerfile:
    buildArgs:
      TEST_ARGUMENT: example value