harness:
  subdomain: samples
  secured: false
  sentry: true
  port: 80
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  env:
    - name: WORKERS
      value: "3"
  dependencies:
    soft:
      - argo
      - events
  resources:
    - name: my-config
      # src file, relative to ./resources
      src: "myConfig.json"
      # dst file, target path in mounted volume of pod
      dst: "/tmp/myConfig.json"

