harness:
  subdomain: samples
  secured: true
  sentry: true
  port: 80
  service:
    port: 8080
    auto: true
  deployment:
    auto: true
    port: 8080
  uri_role_mapping:
    - uri: /
      white-listed: true
    - uri: /api/error
      white-listed: true
    - uri: /api/ping
      white-listed: true
    - uri: /icon.png
      white-listed: true
    - uri: /js/*
      white-listed: true
    - uri: /assets/*
      white-listed: true
  env:
    - name: WORKERS
      value: "3"
  dependencies:
    soft:
      - workflows
      - events
      - accounts 
    build:
      - cloudharness-flask
      - cloudharness-frontend-build
  resources:
    - name: my-config
      src: "myConfig.json"
      dst: "/tmp/resources/myConfig.json"
    - name: example
      src: "example.yaml"
      dst: "/usr/src/app/important_config.yaml"
  secrets:
    asecret: "value"
