# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import cloudharness_cli.samples
from cloudharness_cli.samples.models.inline_response202_task import InlineResponse202Task  # noqa: E501
from cloudharness_cli.samples.rest import ApiException

class TestInlineResponse202Task(unittest.TestCase):
    """InlineResponse202Task unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test InlineResponse202Task
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = cloudharness_cli.samples.models.inline_response202_task.InlineResponse202Task()  # noqa: E501
        if include_optional :
            return InlineResponse202Task(
                href = 'http://workflows.cloudharness.metacell.us/api/operation/my-op', 
                name = 'my-op'
            )
        else :
            return InlineResponse202Task(
        )

    def testInlineResponse202Task(self):
        """Test InlineResponse202Task"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
