# coding: utf-8

"""
    CloudHarness Sample API

    CloudHarness Sample api  # noqa: E501

    The version of the OpenAPI document: 0.1.0
    Contact: cloudharness@metacell.us
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import cloudharness_cli.samples
from cloudharness_cli.samples.api.workflows_api import WorkflowsApi  # noqa: E501
from cloudharness_cli.samples.rest import ApiException


class TestWorkflowsApi(unittest.TestCase):
    """WorkflowsApi unit test stubs"""

    def setUp(self):
        self.api = cloudharness_cli.samples.api.workflows_api.WorkflowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_error(self):
        """Test case for error

        test sentry is working  # noqa: E501
        """
        pass

    def test_submit_async(self):
        """Test case for submit_async

        Send an asynchronous operation  # noqa: E501
        """
        pass

    def test_submit_sync(self):
        """Test case for submit_sync

        Send a synchronous operation  # noqa: E501
        """
        pass

    def test_submit_sync_with_results(self):
        """Test case for submit_sync_with_results

        Send a synchronous operation and get results using the event queue. Just a sum, but in the cloud  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
