apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.apps.sentry.postfix.name }}
  labels:
    app: {{ .Values.apps.sentry.postfix.name }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
   - port: {{ .Values.apps.sentry.postfix.port }}
  selector:
   app: {{ .Values.apps.sentry.postfix.name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.apps.sentry.postfix.name | quote }}
  labels:
    app: {{ .Values.apps.sentry.postfix.name | quote }}
{{ include "deploy_utils.labels" $ | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.apps.sentry.postfix.name | quote }}
{{ include "deploy_utils.labels" $ | indent 6 }}
  template:
    metadata:
      {{- if .Values.apps.sentry.postfix.harvest }}
      annotations:
        co.elastic.logs/enabled: "true"
        metricbeat: "true"
      {{- end }}
      labels:
        app: {{ .Values.apps.sentry.postfix.name | quote }}
{{ include "deploy_utils.labels" $ | indent 8 }}
    spec:
      {{ if .Values.codefresh }}
      imagePullSecrets:
      - name: {{ .Values.codefresh.secret }}
      {{- end }}
      containers:
      - name: {{ .Values.apps.sentry.postfix.name | default "sentry-postfix" | quote }}
        image: {{ .Values.apps.sentry.postfix.image }}
        imagePullPolicy: {{ include "deploy_utils.pullpolicy" .root }}
        env:
        - name: MTP_HOST
          value: {{ printf "mail.%s" .Values.domain }}
            {{- include "deploy_utils.env" .root | nindent 8 }}
            {{- include "deploy_utils.privenv" .root | nindent 8 }}
        ports:
          - containerPort: {{ .Values.apps.sentry.postfix.port | default 25 }}
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
